// Code generated by `platy dev generate`. DO NOT EDIT.
//
// Typed service-to-service client for the cloudflare application. The factories
// are thin bindings over the SDK connector transport, which owns every
// cross-cutting concern — caller validation, identity chaining, token
// attachment, boundary logging, and trace propagation — so neither this
// generated layer nor application code ever re-implements it.
import type { Client } from "@connectrpc/connect";

import {
  connectorServiceClient,
  type ConnectorConfig,
  type Identity,
  type ProxyTarget,
} from "../../../sdk/ts/src";
import { DeviceService } from "../server/cloudflare/v1/cloudflare_pb";
import { WorkerService } from "../server/cloudflare/v1/cloudflare_pb";

export const APPLICATION = "cloudflare";
export const RPC_PREFIX = "/cloudflare.v1.";

// Connection to this application for one hop; application is fixed.
export type Connection = Omit<ConnectorConfig, "application">;

export const createDeviceServiceClient = (connection: Connection, identity: Identity): Client<typeof DeviceService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, DeviceService);

export const createWorkerServiceClient = (connection: Connection, identity: Identity): Client<typeof WorkerService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, WorkerService);

// proxyTarget plugs this application into a sessionProxy (BFF) hop.
export const proxyTarget = (target: { endpoint: string; scopes?: string[]; fetch?: typeof fetch }): ProxyTarget => ({
  prefix: RPC_PREFIX,
  application: APPLICATION,
  ...target,
});
