// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import type { Client } from "@connectrpc/connect";

import { DeviceService } from "../server/cloudflare/v1/device_service_pb";
import { WorkerService } from "../server/cloudflare/v1/worker_service_pb";
import {
  connectorServiceClient,
  type ConnectorConfig,
  type Identity,
  type ProxyTarget,
} from "../../../sdk/ts/src";

export const APPLICATION = "cloudflare";
export const RPC_PREFIX = "/cloudflare.v1.";

export type Connection = Omit<ConnectorConfig, "application">;

export const deviceServiceClient = (
  connection: Connection,
  identity: Identity,
): Client<typeof DeviceService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, DeviceService);

export const workerServiceClient = (
  connection: Connection,
  identity: Identity,
): Client<typeof WorkerService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, WorkerService);

export const proxyTarget = (target: { endpoint: string; scopes?: string[]; fetch?: typeof fetch }): ProxyTarget => ({
  prefix: RPC_PREFIX,
  application: APPLICATION,
  ...target,
});

