// Code generated by `platy dev generate`. DO NOT EDIT.
//
// Typed service-to-service client for the ragbot application. The factories
// are thin bindings over the SDK connector transport, which owns every
// cross-cutting concern — caller validation, identity chaining, token
// attachment, boundary logging, and trace propagation — so neither this
// generated layer nor application code ever re-implements it.
import type { Client } from "@connectrpc/connect";

import {
  connectorServiceClient,
  type ConnectorConfig,
  type Identity,
  type ProxyTarget,
} from "../../../sdk/ts/src";
import { ChatService } from "../server/ragbot/v1/ragbot_pb";
import { ConfigService } from "../server/ragbot/v1/ragbot_pb";
import { DatabaseService } from "../server/ragbot/v1/ragbot_pb";
import { GatewayControlService } from "../server/ragbot/v1/ragbot_pb";
import { InteractionService } from "../server/ragbot/v1/ragbot_pb";
import { LeaderboardService } from "../server/ragbot/v1/ragbot_pb";

export const APPLICATION = "ragbot";
export const RPC_PREFIX = "/ragbot.v1.";

// Connection to this application for one hop; application is fixed.
export type Connection = Omit<ConnectorConfig, "application">;

export const createChatServiceClient = (connection: Connection, identity: Identity): Client<typeof ChatService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, ChatService);

export const createConfigServiceClient = (connection: Connection, identity: Identity): Client<typeof ConfigService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, ConfigService);

export const createDatabaseServiceClient = (connection: Connection, identity: Identity): Client<typeof DatabaseService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, DatabaseService);

export const createGatewayControlServiceClient = (connection: Connection, identity: Identity): Client<typeof GatewayControlService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, GatewayControlService);

export const createInteractionServiceClient = (connection: Connection, identity: Identity): Client<typeof InteractionService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, InteractionService);

export const createLeaderboardServiceClient = (connection: Connection, identity: Identity): Client<typeof LeaderboardService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, LeaderboardService);

// proxyTarget plugs this application into a sessionProxy (BFF) hop.
export const proxyTarget = (target: { endpoint: string; scopes?: string[]; fetch?: typeof fetch }): ProxyTarget => ({
  prefix: RPC_PREFIX,
  application: APPLICATION,
  ...target,
});
