// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import type { Client } from "@connectrpc/connect";

import { ChatService } from "../server/ragbot/v1/chat_service_pb";
import { ConfigService } from "../server/ragbot/v1/config_service_pb";
import { DatabaseService } from "../server/ragbot/v1/database_service_pb";
import { GatewayControlService } from "../server/ragbot/v1/gateway_control_service_pb";
import { InteractionService } from "../server/ragbot/v1/interaction_service_pb";
import { LeaderboardService } from "../server/ragbot/v1/leaderboard_service_pb";
import {
  connectorServiceClient,
  type ConnectorConfig,
  type Identity,
} from "@platy/sdk";

export const APPLICATION = "ragbot";
export const RPC_PREFIX = "/ragbot.v1.";

export type Connection = Omit<ConnectorConfig, "application">;

export const ragbot = {
  chatServiceClient: (connection: Connection, identity: Identity): Client<typeof ChatService> =>
    connectorServiceClient({ ...connection, application: APPLICATION }, identity, ChatService),
  configServiceClient: (connection: Connection, identity: Identity): Client<typeof ConfigService> =>
    connectorServiceClient({ ...connection, application: APPLICATION }, identity, ConfigService),
  databaseServiceClient: (connection: Connection, identity: Identity): Client<typeof DatabaseService> =>
    connectorServiceClient({ ...connection, application: APPLICATION }, identity, DatabaseService),
  gatewayControlServiceClient: (connection: Connection, identity: Identity): Client<typeof GatewayControlService> =>
    connectorServiceClient({ ...connection, application: APPLICATION }, identity, GatewayControlService),
  interactionServiceClient: (connection: Connection, identity: Identity): Client<typeof InteractionService> =>
    connectorServiceClient({ ...connection, application: APPLICATION }, identity, InteractionService),
  leaderboardServiceClient: (connection: Connection, identity: Identity): Client<typeof LeaderboardService> =>
    connectorServiceClient({ ...connection, application: APPLICATION }, identity, LeaderboardService),
};

