export {
  anyAuthenticator,
  bearerToken,
  CLIENT_INSTANCE_HEADER,
  clientInstance,
  createWebBffWorker,
  oidcAuthenticator,
  platformAuthenticator,
  proxyTargetFor,
  sessionChainAuthenticator,
  sessionProxy,
  stsAuthenticator,
  verifySessionRequest,
  type Authenticator,
  type PlatformAuthEnv,
  type ProxyTarget,
  type SessionChainConfig,
  type SessionProxy,
  type SessionProxyConfig,
  type WebBffConfig,
  type WebBffEnv,
  type WebBffTarget,
} from "./auth";
export {
  actorChainRefusal,
  applicationFromClientId,
  defaultScope,
  delegationGraph,
  delegationGraphFromDiscovery,
  hasScope,
  protect,
  requireExpectedActorChain,
  requireIdentity,
  requireSenderConstraint,
  scopeMatches,
  verifyMintedToken,
  type AuthPolicy,
  type DelegationGraph,
} from "./resource";
export {
  ClientError,
  ConnectorAuthError,
  connectorServiceClient,
  connectorToken,
  createClient,
  serviceConnection,
  ttlCache,
  type ClientConfig,
  type ConnectorConfig,
  type PlatformClient,
  type ServiceConnectionEnv,
  type ServiceConnectionTarget,
  type TokenSource,
  type TtlCache,
} from "./client";
export {
  accessOidcProvider,
  actorChainFromClaim,
  actorToken,
  chainExchange,
  createDpopProof,
  DPOP_HEADER,
  dpopThumbprint,
  exchangeProviderAccessToken,
  exchangeToken,
  generateDpopKey,
  loadServiceCredentialFromEnv,
  remoteJwks,
  serviceCredentialFromEnv,
  stsJwksUrl,
  TOKEN_TYPE_ACCESS_TOKEN,
  TOKEN_TYPE_JWT,
  TOKEN_TYPE_SERVICE_CREDENTIAL,
  verifyDpopProof,
  verifyOidcToken,
  verifyStsToken,
  type DpopKey,
  type DpopProof,
  type ExchangedToken,
  type ExchangeRequest,
  type OidcProviderConfig,
  type ProviderAccessToken,
  type RequestDescriptor,
  type ServiceCredential,
  type ServiceCredentialEnv,
  type StsVerifierConfig,
} from "./oauth2";
export { requireSecret, resolveSecret, type SecretsStoreSecret, type WorkerSecret } from "./secrets/store";
export {
  identityExchanged,
  identityExchangeRefused,
  identityKey,
  principalFromIdentity,
  type Identity,
  type IdentityExchangeLog,
  type IdentityKind,
  type Principal,
} from "./identity";
export {
  COMMUNITY_SESSION_SCOPE,
  communitySessionRequiresActor,
  directExchangeGrants,
  INTERNAL_SESSION_SCOPE,
  isCommunitySession,
  isInternalSession,
  sessionScopeForTier,
  sessionTierFromIdentity,
  sessionTierFromScope,
  type SessionTier,
} from "./session-tier";
export { errorMessage, logger } from "./logger";
export {
  annotateSpan,
  createTracer,
  currentSpanContext,
  formatTraceparent,
  gatewayTraceExporter,
  parseTraceparent,
  traceHeaders,
  traceRpc,
  tracerFromEnv,
  type OtelEnv,
  type Span,
  type SpanContext,
  type SpanData,
  type SpanKind,
  type SpanOptions,
  type Tracer,
  type TracerConfig,
} from "./otel";
export {
  providerApiClient,
  providerApiToken,
  ProviderApiAuthError,
  type ProviderApiAuth,
  type ProviderApiConfig,
} from "./provider/api";
export { createRpcHandler, type RpcHandler } from "./resource/router";
export {
  createPlatformRpcWorker,
  type PlatformRpcWorkerConfig,
  type PlatformRpcWorkerEnv,
} from "./worker";
export {
  secretsMatch,
  verifySignedWebhook,
  type WebhookVerifierConfig,
} from "./verify";
