export {
  anyAuthenticator,
  bearerToken,
  CLIENT_INSTANCE_HEADER,
  clientInstance,
  defaultScope,
  oidcAuthenticator,
  protect,
  requireIdentity,
  requireSenderConstraint,
  sessionChainAuthenticator,
  sessionProxy,
  stsAuthenticator,
  verifySessionRequest,
  type Authenticator,
  type AuthPolicy,
  type ProxyTarget,
  type SessionChainConfig,
  type SessionProxy,
  type SessionProxyConfig,
} from "./auth";
export {
  chainedTokenSource,
  chainExchange,
  ClientError,
  ConnectorAuthError,
  connectorClient,
  connectorServiceClient,
  connectorToken,
  connectorTransport,
  createClient,
  exchangeToken,
  serviceCredentialFromEnv,
  serviceTokenSource,
  type ClientConfig,
  type ConnectorConfig,
  type ExchangedToken,
  type ExchangeRequest,
  type PlatformClient,
  type ServiceCredential,
  type TokenSource,
} from "./client";
export { hasScope, identityKey, scopeMatches, type Identity, type IdentityKind } from "./identity";
export { errorMessage, logger } from "./logger";
export {
  annotateSpan,
  createTracer,
  currentSpanContext,
  formatTraceparent,
  gatewayTraceExporter,
  parseTraceparent,
  traceHeaders,
  traceRpc,
  tracerFromEnv,
  type OtelEnv,
  type Span,
  type SpanContext,
  type SpanData,
  type SpanKind,
  type SpanOptions,
  type Tracer,
  type TracerConfig,
} from "./otel";
export { createRpcHandler, type RpcHandler } from "./router";
export {
  accessOidcProvider,
  actorChainFromClaim,
  createDpopProof,
  DPOP_HEADER,
  dpopThumbprint,
  generateDpopKey,
  remoteJwks,
  secretsMatch,
  stsJwksUrl,
  TOKEN_TYPE_ACCESS_TOKEN,
  TOKEN_TYPE_JWT,
  TOKEN_TYPE_SERVICE_CREDENTIAL,
  verifyDpopProof,
  verifyOidcToken,
  verifySignedWebhook,
  verifyStsToken,
  type DpopKey,
  type DpopProof,
  type OidcProviderConfig,
  type RequestDescriptor,
  type StsVerifierConfig,
  type WebhookVerifierConfig,
} from "./verify";
