CREATE TABLE IF NOT EXISTS rag_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ragged_user_id TEXT NOT NULL,
  ragged_username TEXT,
  reported_by_user_id TEXT NOT NULL,
  reported_by_username TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rag_totals (
  ragged_user_id TEXT PRIMARY KEY,
  ragged_username TEXT,
  rag_count INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rag_roasts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  roast_text TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
