// Code generated by platy bffgen. DO NOT EDIT.

import { createWebBffWorker } from "@platy/sdk";

export default createWebBffWorker({
  app: "console",
  targets: [
    {
      audience: "deploy",
      binding: "DEPLOY",
      endpoint: "DEPLOY_ENDPOINT",
      scopes: [
        "deploy/DeployService.ListWorkers",
        "deploy/DeployService.DeployWorker",
      ],
    },
    {
      audience: "discovery",
      binding: "DISCOVERY",
      endpoint: "DISCOVERY_ENDPOINT",
      scopes: [
        "discovery/DiscoveryService.Query",
        "discovery/DiscoveryService.Sync",
      ],
    },
    {
      audience: "ragbot",
      binding: "RAGBOT",
      endpoint: "RAGBOT_ENDPOINT",
      scopes: [
        "ragbot/ConfigService.ListConfig",
        "ragbot/ConfigService.GetConfig",
        "ragbot/ConfigService.UpdateConfig",
        "ragbot/ConfigService.ResetConfig",
        "ragbot/GatewayControlService.GetHealth",
      ],
    },
  ],
});
