/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The dev-proxy single-page admin UI
         * @description Serves the self-contained page with a "Sign in with Discord" button and the command form. Behind Cloudflare Access; the page drives Better Auth's login endpoints and posts commands with the session cookie.
         */
        get: operations["devProxyPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Proxy a slash command through the gateway
         * @description Runs a command through the production gateway → brain path, authorized as the authenticated Discord user. Requires BOTH a valid Access token AND a Better Auth session that is bound to the same Access identity. The response is the gateway's command result relayed verbatim.
         */
        post: operations["devProxyCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CommandOption: {
            /** @description Slash-command option name. */
            name: string;
            /** @description Option value (coerced by the command layer as a Discord option). */
            value: string;
        };
        CommandRequest: {
            /** @description Slash-command name (e.g. ask, rag, ragboard). */
            command: string;
            /** @description Optional Discord channel id the command targets. */
            channelId?: string;
            options?: components["schemas"]["CommandOption"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    devProxyPage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    devProxyCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandRequest"];
            };
        };
        responses: {
            /** @description Command result (a Discord interaction response payload). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Malformed command request body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing/invalid Access token, or no valid Better Auth session, or a session presented under a different Access identity than it was bound to (cross-identity replay). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The acting Discord subject is not allowed by the gateway. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream gateway error. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
