// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import { serviceConnection, type Identity, type ServiceConnectionEnv } from "@platy/sdk";
import { idp } from "../../idp/service";

type Fetcher = { fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> };

export type TargetsEnv = ServiceConnectionEnv & {
};

const idpConnection = (env: TargetsEnv) =>
  serviceConnection(env, {
    endpoint: env.AUTH_GATEWAY_URL,
    binding: env.AUTH_GATEWAY,
    scopes: ["idp/DiscoveryService.Discover"],
  });

export const targets = (env: TargetsEnv, identity: Identity) => ({
  idp: {
    discoveryService: async () => {
      const connection = await idpConnection(env);
      if (!connection) {
        throw new Error("idp service connection unavailable (missing endpoint or credential)");
      }
      return idp.discoveryServiceClient(connection, identity);
    },
  },
});
