// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import type { Client } from "@connectrpc/connect";
import type { DescService } from "@bufbuild/protobuf";

import {
  connectorServiceClient,
  type ConnectorConfig,
  type Identity,
  type ProxyTarget,
} from "../../../sdk/ts/src";

export const APPLICATION = "idp";
export const RPC_PREFIX = "/idp.v1.";

export type Connection = Omit<ConnectorConfig, "application">;

export const serviceClient = <S extends DescService>(
  connection: Connection,
  identity: Identity,
  service: S,
): Client<S> => connectorServiceClient({ ...connection, application: APPLICATION }, identity, service);

export const proxyTarget = (target: { endpoint: string; scopes?: string[]; fetch?: typeof fetch }): ProxyTarget => ({
  prefix: RPC_PREFIX,
  application: APPLICATION,
  ...target,
});

