// Code generated by `platy dev generate`. DO NOT EDIT.
//
// Typed service-to-service client for the idp application. The factories
// are thin bindings over the SDK connector transport, which owns every
// cross-cutting concern — caller validation, identity chaining, token
// attachment, boundary logging, and trace propagation — so neither this
// generated layer nor application code ever re-implements it.
import type { Client } from "@connectrpc/connect";

import {
  connectorServiceClient,
  type ConnectorConfig,
  type Identity,
  type ProxyTarget,
} from "../../../sdk/ts/src";
import { ClientIdentityService } from "../server/idp/v1/idp_pb";
import { DiscoveryService } from "../server/idp/v1/idp_pb";
import { IdentityService } from "../server/idp/v1/idp_pb";
import { RegistryService } from "../server/idp/v1/idp_pb";
import { TraceService } from "../server/idp/v1/idp_pb";

export const APPLICATION = "idp";
export const RPC_PREFIX = "/idp.v1.";

// Connection to this application for one hop; application is fixed.
export type Connection = Omit<ConnectorConfig, "application">;

export const createClientIdentityServiceClient = (connection: Connection, identity: Identity): Client<typeof ClientIdentityService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, ClientIdentityService);

export const createDiscoveryServiceClient = (connection: Connection, identity: Identity): Client<typeof DiscoveryService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, DiscoveryService);

export const createIdentityServiceClient = (connection: Connection, identity: Identity): Client<typeof IdentityService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, IdentityService);

export const createRegistryServiceClient = (connection: Connection, identity: Identity): Client<typeof RegistryService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, RegistryService);

export const createTraceServiceClient = (connection: Connection, identity: Identity): Client<typeof TraceService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, TraceService);

// proxyTarget plugs this application into a sessionProxy (BFF) hop.
export const proxyTarget = (target: { endpoint: string; scopes?: string[]; fetch?: typeof fetch }): ProxyTarget => ({
  prefix: RPC_PREFIX,
  application: APPLICATION,
  ...target,
});
