// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import type { Client } from "@connectrpc/connect";

import { ClientIdentityService } from "../server/idp/v1/client_identity_service_pb";
import { DiscoveryService } from "../server/idp/v1/gateway_discovery_service_pb";
import { IdentityService } from "../server/idp/v1/identity_service_pb";
import { RegistryService } from "../server/idp/v1/registry_service_pb";
import { TraceService } from "../server/idp/v1/trace_service_pb";
import {
  connectorServiceClient,
  type ConnectorConfig,
  type Identity,
} from "../../../sdk/ts/src";

export const APPLICATION = "idp";
export const RPC_PREFIX = "/idp.v1.";

export type Connection = Omit<ConnectorConfig, "application">;

export const clientIdentityServiceClient = (
  connection: Connection,
  identity: Identity,
): Client<typeof ClientIdentityService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, ClientIdentityService);

export const discoveryServiceClient = (
  connection: Connection,
  identity: Identity,
): Client<typeof DiscoveryService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, DiscoveryService);

export const identityServiceClient = (
  connection: Connection,
  identity: Identity,
): Client<typeof IdentityService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, IdentityService);

export const registryServiceClient = (
  connection: Connection,
  identity: Identity,
): Client<typeof RegistryService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, RegistryService);

export const traceServiceClient = (
  connection: Connection,
  identity: Identity,
): Client<typeof TraceService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, TraceService);


