// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import { serviceConnection, type Identity, type ServiceConnectionEnv } from "@platy/sdk";
import { aigateway } from "../../aigateway/service";
import { deploy } from "../../deploy/service";

type Fetcher = { fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> };

export type TargetsEnv = ServiceConnectionEnv & {
  AIGATEWAY?: Fetcher;
  AIGATEWAY_ENDPOINT?: string;
  DEPLOY?: Fetcher;
  DEPLOY_ENDPOINT?: string;
};

const aigatewayConnection = (env: TargetsEnv) =>
  serviceConnection(env, {
    endpoint: env.AIGATEWAY_ENDPOINT,
    binding: env.AIGATEWAY,
    scopes: ["aigateway/ChatService.Complete", "aigateway/ChatService.StreamComplete"],
  });

const deployConnection = (env: TargetsEnv) =>
  serviceConnection(env, {
    endpoint: env.DEPLOY_ENDPOINT,
    binding: env.DEPLOY,
    scopes: ["deploy/DeployService.ListWorkers"],
  });

// targets returns typed worker-to-worker clients for this app's manifest
// delegations. Each accessor throws when the target's endpoint or this
// worker's service credential is not configured.
export const targets = (env: TargetsEnv, identity: Identity) => ({
  aigateway: {
    chatService: () => {
      const connection = aigatewayConnection(env);
      if (!connection) {
        throw new Error("aigateway service connection unavailable (missing endpoint or credential)");
      }
      return aigateway.chatServiceClient(connection, identity);
    },
  },
  deploy: {
    deployService: () => {
      const connection = deployConnection(env);
      if (!connection) {
        throw new Error("deploy service connection unavailable (missing endpoint or credential)");
      }
      return deploy.deployServiceClient(connection, identity);
    },
  },
});

