// Code generated by `platy dev generate`. DO NOT EDIT.
//
// Typed browser client for the discovery application: binds the generated
// Connect services to the trust zone web auth SDK. The page stays a dumb
// client — it only needs an initialized TrustZoneWebAuth; the application
// mints its own audience token server-side (session-chain pattern).
import type { Client } from "@connectrpc/connect";

import { webClient, type TrustZoneWebAuth, type WebClientOptions } from "../../../sdk/web/src";
import { DiscoveryService } from "../server/discovery/v1/discovery_pb";

export const APPLICATION = "discovery";

export const createDiscoveryServiceClient = (auth: TrustZoneWebAuth, options?: WebClientOptions): Client<typeof DiscoveryService> =>
  webClient(auth, APPLICATION, DiscoveryService, options);
