// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import type { Client } from "@connectrpc/connect";
import type { DescService } from "@bufbuild/protobuf";

import { webClient, type TrustZoneWebAuth, type WebClientOptions } from "../../../sdk/web/src";

export const APPLICATION = "discovery";

export const client = <S extends DescService>(
  auth: TrustZoneWebAuth,
  service: S,
  options?: WebClientOptions,
): Client<S> => webClient(auth, APPLICATION, service, options);

export * from "../graphql";

