// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import type { Client } from "@connectrpc/connect";

import { DiscoveryService } from "../server/discovery/v1/discovery_service_pb";
import { webClient, type BrowserAuth, type WebClientOptions } from "@platy/web";

export const APPLICATION = "discovery";

export const discovery = {
  discoveryServiceClient: (auth: BrowserAuth, options?: WebClientOptions): Client<typeof DiscoveryService> =>
    webClient(auth, APPLICATION, DiscoveryService, options),
};

export * from "../graphql";

