// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import { serviceConnection, type Identity, type ServiceConnectionEnv } from "@platy/sdk";
import { cloudflare } from "../../cloudflare/service";

type Fetcher = { fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> };

export type TargetsEnv = ServiceConnectionEnv & {
  CLOUDFLARE?: Fetcher;
  CLOUDFLARE_ENDPOINT?: string;
};

const cloudflareConnection = (env: TargetsEnv) =>
  serviceConnection(env, {
    endpoint: env.CLOUDFLARE_ENDPOINT,
    binding: env.CLOUDFLARE,
    scopes: ["cloudflare/WorkerService.DeployWorker", "cloudflare/WorkerService.ListWorkers"],
  });

export const targets = (env: TargetsEnv, identity: Identity) => ({
  cloudflare: {
    workerService: async () => {
      const connection = await cloudflareConnection(env);
      if (!connection) {
        throw new Error("cloudflare service connection unavailable (missing endpoint or credential)");
      }
      return cloudflare.workerServiceClient(connection, identity);
    },
  },
});
