// Code generated by `platy dev generate`. DO NOT EDIT.
//
// Typed browser client for the aigateway application: binds the generated
// Connect services to the trust zone web auth SDK. The page stays a dumb
// client — it only needs an initialized TrustZoneWebAuth; the application
// mints its own audience token server-side (session-chain pattern).
import type { Client } from "@connectrpc/connect";

import { webClient, type TrustZoneWebAuth, type WebClientOptions } from "../../../sdk/web/src";
import { ChatService } from "../server/aigateway/v1/aigateway_pb";

export const APPLICATION = "aigateway";

export const createChatServiceClient = (auth: TrustZoneWebAuth, options?: WebClientOptions): Client<typeof ChatService> =>
  webClient(auth, APPLICATION, ChatService, options);
