// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import type { Client } from "@connectrpc/connect";

import { DeployService } from "../server/deploy/v1/deploy_service_pb";
import { webClient, type BrowserAuth, type WebClientOptions } from "@platy/web";

export const APPLICATION = "deploy";

export const deploy = {
  deployServiceClient: (auth: BrowserAuth, options?: WebClientOptions): Client<typeof DeployService> =>
    webClient(auth, APPLICATION, DeployService, options),
};

