// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import type { Client } from "@connectrpc/connect";

import { ClientIdentityService } from "../server/idp/v1/client_identity_service_pb";
import { DiscoveryService } from "../server/idp/v1/gateway_discovery_service_pb";
import { IdentityService } from "../server/idp/v1/identity_service_pb";
import { RegistryService } from "../server/idp/v1/registry_service_pb";
import { TraceService } from "../server/idp/v1/trace_service_pb";
import { webClient, type BrowserAuth, type WebClientOptions } from "@platy/web";

export const APPLICATION = "idp";

export const idp = {
  clientIdentityServiceClient: (auth: BrowserAuth, options?: WebClientOptions): Client<typeof ClientIdentityService> =>
    webClient(auth, APPLICATION, ClientIdentityService, options),
  discoveryServiceClient: (auth: BrowserAuth, options?: WebClientOptions): Client<typeof DiscoveryService> =>
    webClient(auth, APPLICATION, DiscoveryService, options),
  identityServiceClient: (auth: BrowserAuth, options?: WebClientOptions): Client<typeof IdentityService> =>
    webClient(auth, APPLICATION, IdentityService, options),
  registryServiceClient: (auth: BrowserAuth, options?: WebClientOptions): Client<typeof RegistryService> =>
    webClient(auth, APPLICATION, RegistryService, options),
  traceServiceClient: (auth: BrowserAuth, options?: WebClientOptions): Client<typeof TraceService> =>
    webClient(auth, APPLICATION, TraceService, options),
};

