package clientgen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"jsmunro.me/platy/cli/internal/manifest"
)

func Generate(gen *protogen.Plugin, app, root string) error {
	loaded := manifest.Load(root)
	entry, registered := loaded.Applications[app]
	services := serviceBindings(gen, app)

	webEnabled := registered && entry.WebClient
	serviceEnabled := registered && entry.ServiceClient

	if webEnabled || serviceEnabled {
		if len(services) == 0 {
			return fmt.Errorf("no service declarations under infra/proto/%s", app)
		}
	}

	extra := extraExports(app, root)
	appRoot := filepath.Join(root, "infra", "applications", app)

	if webEnabled {
		emitGeneratedFile(gen, "web/index.ts", renderWeb(app, services, extra))
	} else if err := os.RemoveAll(filepath.Join(appRoot, "web")); err != nil {
		return fmt.Errorf("remove stale web client for %s: %w", app, err)
	}

	if serviceEnabled {
		emitGeneratedFile(gen, "service/index.ts", renderService(app, services, extra))
	} else if err := os.RemoveAll(filepath.Join(appRoot, "service")); err != nil {
		return fmt.Errorf("remove stale service client for %s: %w", app, err)
	}

	if registered && len(services) > 0 {
		emitGeneratedFile(gen, "policy.generated.md", renderPolicy(app, entry, services))
	}

	return nil
}

type serviceBinding struct {
	Name        string
	FactoryName string
	ImportPath  string
	Methods     []methodBinding
}

type methodBinding struct {
	Name  string
	Scope string
}

func serviceBindings(gen *protogen.Plugin, app string) []serviceBinding {
	var bindings []serviceBinding
	for _, file := range gen.Files {
		if !file.Generate {
			continue
		}
		importPath := "../server/" + strings.TrimSuffix(file.Desc.Path(), ".proto") + "_pb"
		for _, service := range file.Services {
			binding := serviceBinding{
				Name:        service.GoName,
				FactoryName: lowerFirst(service.GoName) + "Client",
				ImportPath:  importPath,
			}
			for _, method := range service.Methods {
				binding.Methods = append(binding.Methods, methodBinding{
					Name:  method.GoName,
					Scope: defaultScope(app, service.GoName, method.GoName),
				})
			}
			bindings = append(bindings, binding)
		}
	}
	sort.Slice(bindings, func(i, j int) bool { return bindings[i].Name < bindings[j].Name })
	return bindings
}

func defaultScope(app, service, method string) string {
	return fmt.Sprintf("%s/%s.%s", app, service, method)
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	return strings.ToLower(value[:1]) + value[1:]
}

func extraExports(app, root string) string {
	graphqlIndex := filepath.Join(root, "infra", "applications", app, "graphql", "index.ts")
	if _, err := os.Stat(graphqlIndex); err == nil {
		return "\nexport * from \"../graphql\";\n"
	}
	return ""
}

func renderService(app string, services []serviceBinding, extra string) string {
	var b strings.Builder
	b.WriteString("// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.\n")
	b.WriteString("import type { Client } from \"@connectrpc/connect\";\n\n")
	for _, service := range services {
		fmt.Fprintf(&b, "import { %s } from %q;\n", service.Name, service.ImportPath)
	}
	b.WriteString("import {\n")
	b.WriteString("  connectorServiceClient,\n")
	b.WriteString("  type ConnectorConfig,\n")
	b.WriteString("  type Identity,\n")
	b.WriteString("} from \"../../../sdk/ts/src\";\n\n")
	fmt.Fprintf(&b, "export const APPLICATION = %q;\n", app)
	fmt.Fprintf(&b, "export const RPC_PREFIX = \"/%s.v1.\";\n\n", app)
	b.WriteString("export type Connection = Omit<ConnectorConfig, \"application\">;\n\n")
	for _, service := range services {
		fmt.Fprintf(&b, "export const %s = (\n", service.FactoryName)
		b.WriteString("  connection: Connection,\n")
		b.WriteString("  identity: Identity,\n")
		fmt.Fprintf(&b, "): Client<typeof %s> =>\n", service.Name)
		fmt.Fprintf(&b, "  connectorServiceClient({ ...connection, application: APPLICATION }, identity, %s);\n\n", service.Name)
	}
	b.WriteString(extra)
	return b.String()
}

func renderWeb(app string, services []serviceBinding, extra string) string {
	var b strings.Builder
	b.WriteString("// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.\n")
	b.WriteString("import type { Client } from \"@connectrpc/connect\";\n\n")
	for _, service := range services {
		fmt.Fprintf(&b, "import { %s } from %q;\n", service.Name, service.ImportPath)
	}
	b.WriteString("import { webClient, type TrustZoneWebAuth, type WebClientOptions } from \"../../../sdk/web/src\";\n\n")
	fmt.Fprintf(&b, "export const APPLICATION = %q;\n\n", app)
	for _, service := range services {
		fmt.Fprintf(&b, "export const %s = (\n", service.FactoryName)
		b.WriteString("  auth: TrustZoneWebAuth,\n")
		b.WriteString("  options?: WebClientOptions,\n")
		fmt.Fprintf(&b, "): Client<typeof %s> => webClient(auth, APPLICATION, %s, options);\n\n", service.Name, service.Name)
	}
	b.WriteString(extra)
	return b.String()
}

func renderPolicy(app string, entry manifest.Application, services []serviceBinding) string {
	var b strings.Builder
	b.WriteString("<!-- Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT. -->\n")
	fmt.Fprintf(&b, "# %s Policy\n\n", app)
	fmt.Fprintf(&b, "- Application: `%s`\n", app)
	fmt.Fprintf(&b, "- Description: %s\n", entry.Description)
	fmt.Fprintf(&b, "- Endpoint: `%s`\n", entry.Endpoint)
	fmt.Fprintf(&b, "- Worker: `%s`\n", entry.Worker)
	fmt.Fprintf(&b, "- Trust zone: `%s`\n", entry.ResolvedTrustZone())
	fmt.Fprintf(&b, "- Provider auth: `%s`\n", entry.ProviderAuthMode())
	fmt.Fprintf(&b, "- Impersonatable: `%t`\n", entry.AllowsImpersonation())
	fmt.Fprintf(&b, "- Service client generated: `%t`\n", entry.ServiceClient)
	fmt.Fprintf(&b, "- Web client generated: `%t`\n\n", entry.WebClient)
	b.WriteString("## Resources\n\n")
	for _, service := range services {
		fmt.Fprintf(&b, "### %s\n\n", service.Name)
		for _, method := range service.Methods {
			fmt.Fprintf(&b, "- `%s` -> `%s`\n", method.Name, method.Scope)
		}
		b.WriteString("\n")
	}
	b.WriteString("## Delegations\n\n")
	if len(entry.Delegations) == 0 {
		b.WriteString("- none\n\n")
	} else {
		for _, delegation := range entry.Delegations {
			fmt.Fprintf(&b, "- `%s`", delegation.Audience)
			if len(delegation.Scopes) == 0 {
				b.WriteString(" -> all registered scopes\n")
				continue
			}
			b.WriteString("\n")
			for _, scope := range delegation.Scopes {
				fmt.Fprintf(&b, "  - `%s`\n", scope)
			}
		}
		b.WriteString("\n")
	}
	b.WriteString("## Secrets\n\n")
	if len(entry.Secrets) == 0 {
		b.WriteString("- none\n\n")
	} else {
		keys := make([]string, 0, len(entry.Secrets))
		for key := range entry.Secrets {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			fmt.Fprintf(&b, "- `%s`\n", key)
		}
		b.WriteString("\n")
	}
	b.WriteString("## Post Deploy\n\n")
	if len(entry.PostDeploy) == 0 {
		b.WriteString("- none\n")
	} else {
		for _, hook := range entry.PostDeploy {
			fmt.Fprintf(&b, "- `%s`\n", hook)
		}
	}
	return b.String()
}

func emitGeneratedFile(gen *protogen.Plugin, relativePath, content string) {
	generated := gen.NewGeneratedFile(relativePath, "")
	for _, line := range strings.Split(content, "\n") {
		generated.P(line)
	}
}
