// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0x84bf4a759a05daf3n;
/**
* thread_start / thread_reply / channel_reply / ask jobs.
*
*/
export class ChatPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "ChatPayload",
    id: "a184a57b4d766c6d",
    size: new $.ObjectSize(0, 6),
  };
  get channelId(): string {
    return $.utils.getText(0, this);
  }
  set channelId(value: string) {
    $.utils.setText(0, value, this);
  }
  get messageId(): string {
    return $.utils.getText(1, this);
  }
  set messageId(value: string) {
    $.utils.setText(1, value, this);
  }
  get botUserId(): string {
    return $.utils.getText(2, this);
  }
  set botUserId(value: string) {
    $.utils.setText(2, value, this);
  }
  get prompt(): string {
    return $.utils.getText(3, this);
  }
  set prompt(value: string) {
    $.utils.setText(3, value, this);
  }
  get replyMessageId(): string {
    return $.utils.getText(4, this);
  }
  set replyMessageId(value: string) {
    $.utils.setText(4, value, this);
  }
  get replyChannelId(): string {
    return $.utils.getText(5, this);
  }
  set replyChannelId(value: string) {
    $.utils.setText(5, value, this);
  }
  toString(): string { return "ChatPayload_" + super.toString(); }
}
export class RagjamPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "RagjamPayload",
    id: "dfa667e5158a519b",
    size: new $.ObjectSize(0, 5),
  };
  get applicationId(): string {
    return $.utils.getText(0, this);
  }
  set applicationId(value: string) {
    $.utils.setText(0, value, this);
  }
  get interactionToken(): string {
    return $.utils.getText(1, this);
  }
  set interactionToken(value: string) {
    $.utils.setText(1, value, this);
  }
  get channelId(): string {
    return $.utils.getText(2, this);
  }
  set channelId(value: string) {
    $.utils.setText(2, value, this);
  }
  get prompt(): string {
    return $.utils.getText(3, this);
  }
  set prompt(value: string) {
    $.utils.setText(3, value, this);
  }
  get lyrics(): string {
    return $.utils.getText(4, this);
  }
  set lyrics(value: string) {
    $.utils.setText(4, value, this);
  }
  toString(): string { return "RagjamPayload_" + super.toString(); }
}
export class SpendPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "SpendPayload",
    id: "9e18059a55e07db8",
    size: new $.ObjectSize(0, 1),
  };
  get spendEventId(): string {
    return $.utils.getText(0, this);
  }
  set spendEventId(value: string) {
    $.utils.setText(0, value, this);
  }
  toString(): string { return "SpendPayload_" + super.toString(); }
}
export class EventEnvelope_Actor extends $.Struct {
  static readonly _capnp = {
    displayName: "actor",
    id: "ca483fdaf194ca92",
    size: new $.ObjectSize(8, 8),
  };
  get userId(): string {
    return $.utils.getText(4, this);
  }
  set userId(value: string) {
    $.utils.setText(4, value, this);
  }
  get username(): string {
    return $.utils.getText(5, this);
  }
  set username(value: string) {
    $.utils.setText(5, value, this);
  }
  toString(): string { return "EventEnvelope_Actor_" + super.toString(); }
}
export const EventEnvelope_Payload_Which = {
  THREAD_START: 0,
  THREAD_REPLY: 1,
  CHANNEL_REPLY: 2,
  RAGJAM: 3,
  SPEND: 4,
  ASK: 5
} as const;
export type EventEnvelope_Payload_Which = (typeof EventEnvelope_Payload_Which)[keyof typeof EventEnvelope_Payload_Which];
export class EventEnvelope_Payload extends $.Struct {
  static readonly THREAD_START = EventEnvelope_Payload_Which.THREAD_START;
  static readonly THREAD_REPLY = EventEnvelope_Payload_Which.THREAD_REPLY;
  static readonly CHANNEL_REPLY = EventEnvelope_Payload_Which.CHANNEL_REPLY;
  static readonly RAGJAM = EventEnvelope_Payload_Which.RAGJAM;
  static readonly SPEND = EventEnvelope_Payload_Which.SPEND;
  static readonly ASK = EventEnvelope_Payload_Which.ASK;
  static readonly _capnp = {
    displayName: "payload",
    id: "a636c8f1ec42d04d",
    size: new $.ObjectSize(8, 8),
  };
  _adoptThreadStart(value: $.Orphan<ChatPayload>): void {
    $.utils.setUint16(2, 0, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownThreadStart(): $.Orphan<ChatPayload> {
    return $.utils.disown(this.threadStart);
  }
  get threadStart(): ChatPayload {
    $.utils.testWhich("threadStart", $.utils.getUint16(2, this), 0, this);
    return $.utils.getStruct(7, ChatPayload, this);
  }
  _hasThreadStart(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initThreadStart(): ChatPayload {
    $.utils.setUint16(2, 0, this);
    return $.utils.initStructAt(7, ChatPayload, this);
  }
  get _isThreadStart(): boolean {
    return $.utils.getUint16(2, this) === 0;
  }
  set threadStart(value: ChatPayload) {
    $.utils.setUint16(2, 0, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptThreadReply(value: $.Orphan<ChatPayload>): void {
    $.utils.setUint16(2, 1, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownThreadReply(): $.Orphan<ChatPayload> {
    return $.utils.disown(this.threadReply);
  }
  get threadReply(): ChatPayload {
    $.utils.testWhich("threadReply", $.utils.getUint16(2, this), 1, this);
    return $.utils.getStruct(7, ChatPayload, this);
  }
  _hasThreadReply(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initThreadReply(): ChatPayload {
    $.utils.setUint16(2, 1, this);
    return $.utils.initStructAt(7, ChatPayload, this);
  }
  get _isThreadReply(): boolean {
    return $.utils.getUint16(2, this) === 1;
  }
  set threadReply(value: ChatPayload) {
    $.utils.setUint16(2, 1, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptChannelReply(value: $.Orphan<ChatPayload>): void {
    $.utils.setUint16(2, 2, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownChannelReply(): $.Orphan<ChatPayload> {
    return $.utils.disown(this.channelReply);
  }
  get channelReply(): ChatPayload {
    $.utils.testWhich("channelReply", $.utils.getUint16(2, this), 2, this);
    return $.utils.getStruct(7, ChatPayload, this);
  }
  _hasChannelReply(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initChannelReply(): ChatPayload {
    $.utils.setUint16(2, 2, this);
    return $.utils.initStructAt(7, ChatPayload, this);
  }
  get _isChannelReply(): boolean {
    return $.utils.getUint16(2, this) === 2;
  }
  set channelReply(value: ChatPayload) {
    $.utils.setUint16(2, 2, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptRagjam(value: $.Orphan<RagjamPayload>): void {
    $.utils.setUint16(2, 3, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownRagjam(): $.Orphan<RagjamPayload> {
    return $.utils.disown(this.ragjam);
  }
  get ragjam(): RagjamPayload {
    $.utils.testWhich("ragjam", $.utils.getUint16(2, this), 3, this);
    return $.utils.getStruct(7, RagjamPayload, this);
  }
  _hasRagjam(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initRagjam(): RagjamPayload {
    $.utils.setUint16(2, 3, this);
    return $.utils.initStructAt(7, RagjamPayload, this);
  }
  get _isRagjam(): boolean {
    return $.utils.getUint16(2, this) === 3;
  }
  set ragjam(value: RagjamPayload) {
    $.utils.setUint16(2, 3, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptSpend(value: $.Orphan<SpendPayload>): void {
    $.utils.setUint16(2, 4, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownSpend(): $.Orphan<SpendPayload> {
    return $.utils.disown(this.spend);
  }
  get spend(): SpendPayload {
    $.utils.testWhich("spend", $.utils.getUint16(2, this), 4, this);
    return $.utils.getStruct(7, SpendPayload, this);
  }
  _hasSpend(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initSpend(): SpendPayload {
    $.utils.setUint16(2, 4, this);
    return $.utils.initStructAt(7, SpendPayload, this);
  }
  get _isSpend(): boolean {
    return $.utils.getUint16(2, this) === 4;
  }
  set spend(value: SpendPayload) {
    $.utils.setUint16(2, 4, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptAsk(value: $.Orphan<ChatPayload>): void {
    $.utils.setUint16(2, 5, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownAsk(): $.Orphan<ChatPayload> {
    return $.utils.disown(this.ask);
  }
  get ask(): ChatPayload {
    $.utils.testWhich("ask", $.utils.getUint16(2, this), 5, this);
    return $.utils.getStruct(7, ChatPayload, this);
  }
  _hasAsk(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initAsk(): ChatPayload {
    $.utils.setUint16(2, 5, this);
    return $.utils.initStructAt(7, ChatPayload, this);
  }
  get _isAsk(): boolean {
    return $.utils.getUint16(2, this) === 5;
  }
  set ask(value: ChatPayload) {
    $.utils.setUint16(2, 5, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  toString(): string { return "EventEnvelope_Payload_" + super.toString(); }
  which(): EventEnvelope_Payload_Which {
    return $.utils.getUint16(2, this) as EventEnvelope_Payload_Which;
  }
}
export class EventEnvelope extends $.Struct {
  static readonly _capnp = {
    displayName: "EventEnvelope",
    id: "ea799f50bc6beec6",
    size: new $.ObjectSize(8, 8),
  };
  get v(): number {
    return $.utils.getUint16(0, this);
  }
  set v(value: number) {
    $.utils.setUint16(0, value, this);
  }
  get type(): string {
    return $.utils.getText(0, this);
  }
  set type(value: string) {
    $.utils.setText(0, value, this);
  }
  get id(): string {
    return $.utils.getText(1, this);
  }
  set id(value: string) {
    $.utils.setText(1, value, this);
  }
  get occurredAt(): string {
    return $.utils.getText(2, this);
  }
  set occurredAt(value: string) {
    $.utils.setText(2, value, this);
  }
  get source(): string {
    return $.utils.getText(3, this);
  }
  set source(value: string) {
    $.utils.setText(3, value, this);
  }
  get actor(): EventEnvelope_Actor {
    return $.utils.getAs(EventEnvelope_Actor, this);
  }
  _initActor(): EventEnvelope_Actor {
    return $.utils.getAs(EventEnvelope_Actor, this);
  }
  get guildId(): string {
    return $.utils.getText(6, this);
  }
  set guildId(value: string) {
    $.utils.setText(6, value, this);
  }
  get payload(): EventEnvelope_Payload {
    return $.utils.getAs(EventEnvelope_Payload, this);
  }
  _initPayload(): EventEnvelope_Payload {
    return $.utils.getAs(EventEnvelope_Payload, this);
  }
  toString(): string { return "EventEnvelope_" + super.toString(); }
}
