// Code generated by platy bffgen. DO NOT EDIT.

import { idp } from "../../../idp/service";
import { createWebBffWorker } from "@platy/sdk";

export default createWebBffWorker({
  app: "portal",
  registerClient: idp.clientIdentityServiceClient,
  targets: [
    {
      audience: "aigateway",
      binding: "AIGATEWAY",
      endpoint: "AIGATEWAY_ENDPOINT",
    },
    {
      audience: "ragbot",
      binding: "RAGBOT",
      endpoint: "RAGBOT_ENDPOINT",
      scopes: [
        "ragbot/LeaderboardService.ListTotals",
        "ragbot/InteractionService.ListInteractions",
        "ragbot/ConfigService.ListConfig",
        "ragbot/ConfigService.GetConfig",
        "ragbot/ConfigService.UpdateConfig",
        "ragbot/GatewayControlService.GetHealth",
      ],
    },
  ],
});
