// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import type { Client } from "@connectrpc/connect";

import { ChatService } from "../server/aigateway/v1/chat_service_pb";
import {
  connectorServiceClient,
  type ConnectorConfig,
  type Identity,
} from "../../../sdk/ts/src";

export const APPLICATION = "aigateway";
export const RPC_PREFIX = "/aigateway.v1.";

export type Connection = Omit<ConnectorConfig, "application">;

export const chatServiceClient = (
  connection: Connection,
  identity: Identity,
): Client<typeof ChatService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, ChatService);


