// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import type { Client } from "@connectrpc/connect";

import { DiscoveryService } from "../server/discovery/v1/discovery_service_pb";
import {
  connectorServiceClient,
  type ConnectorConfig,
  type Identity,
} from "../../../sdk/ts/src";

export const APPLICATION = "discovery";
export const RPC_PREFIX = "/discovery.v1.";

export type Connection = Omit<ConnectorConfig, "application">;

export const discoveryServiceClient = (
  connection: Connection,
  identity: Identity,
): Client<typeof DiscoveryService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, DiscoveryService);


export * from "../graphql";

