// Code generated by `platy dev generate`. DO NOT EDIT.
//
// Typed service-to-service client for the discovery application. The factories
// are thin bindings over the SDK connector transport, which owns every
// cross-cutting concern — caller validation, identity chaining, token
// attachment, boundary logging, and trace propagation — so neither this
// generated layer nor application code ever re-implements it.
import type { Client } from "@connectrpc/connect";

import {
  connectorServiceClient,
  type ConnectorConfig,
  type Identity,
  type ProxyTarget,
} from "../../../sdk/ts/src";
import { DiscoveryService } from "../server/discovery/v1/discovery_pb";

export const APPLICATION = "discovery";
export const RPC_PREFIX = "/discovery.v1.";

// Connection to this application for one hop; application is fixed.
export type Connection = Omit<ConnectorConfig, "application">;

export const createDiscoveryServiceClient = (connection: Connection, identity: Identity): Client<typeof DiscoveryService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, DiscoveryService);

// proxyTarget plugs this application into a sessionProxy (BFF) hop.
export const proxyTarget = (target: { endpoint: string; scopes?: string[]; fetch?: typeof fetch }): ProxyTarget => ({
  prefix: RPC_PREFIX,
  application: APPLICATION,
  ...target,
});
