// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0x84bf4a759a05daf3n;
/**
* thread_start / thread_reply / channel_reply / ask jobs.
*
*/
export class ChatPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "ChatPayload",
    id: "a184a57b4d766c6d",
    size: new $.ObjectSize(0, 6),
  };
  get channelId(): string {
    return $.utils.getText(0, this);
  }
  set channelId(value: string) {
    $.utils.setText(0, value, this);
  }
  get messageId(): string {
    return $.utils.getText(1, this);
  }
  set messageId(value: string) {
    $.utils.setText(1, value, this);
  }
  get botUserId(): string {
    return $.utils.getText(2, this);
  }
  set botUserId(value: string) {
    $.utils.setText(2, value, this);
  }
  get prompt(): string {
    return $.utils.getText(3, this);
  }
  set prompt(value: string) {
    $.utils.setText(3, value, this);
  }
  get replyMessageId(): string {
    return $.utils.getText(4, this);
  }
  set replyMessageId(value: string) {
    $.utils.setText(4, value, this);
  }
  get replyChannelId(): string {
    return $.utils.getText(5, this);
  }
  set replyChannelId(value: string) {
    $.utils.setText(5, value, this);
  }
  toString(): string { return "ChatPayload_" + super.toString(); }
}
export class RagjamPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "RagjamPayload",
    id: "dfa667e5158a519b",
    size: new $.ObjectSize(0, 5),
  };
  get applicationId(): string {
    return $.utils.getText(0, this);
  }
  set applicationId(value: string) {
    $.utils.setText(0, value, this);
  }
  get interactionToken(): string {
    return $.utils.getText(1, this);
  }
  set interactionToken(value: string) {
    $.utils.setText(1, value, this);
  }
  get channelId(): string {
    return $.utils.getText(2, this);
  }
  set channelId(value: string) {
    $.utils.setText(2, value, this);
  }
  get prompt(): string {
    return $.utils.getText(3, this);
  }
  set prompt(value: string) {
    $.utils.setText(3, value, this);
  }
  get lyrics(): string {
    return $.utils.getText(4, this);
  }
  set lyrics(value: string) {
    $.utils.setText(4, value, this);
  }
  toString(): string { return "RagjamPayload_" + super.toString(); }
}
export class BicturePayload extends $.Struct {
  static readonly _capnp = {
    displayName: "BicturePayload",
    id: "cdea29560f4b3187",
    size: new $.ObjectSize(0, 4),
  };
  get applicationId(): string {
    return $.utils.getText(0, this);
  }
  set applicationId(value: string) {
    $.utils.setText(0, value, this);
  }
  get interactionToken(): string {
    return $.utils.getText(1, this);
  }
  set interactionToken(value: string) {
    $.utils.setText(1, value, this);
  }
  get channelId(): string {
    return $.utils.getText(2, this);
  }
  set channelId(value: string) {
    $.utils.setText(2, value, this);
  }
  get prompt(): string {
    return $.utils.getText(3, this);
  }
  set prompt(value: string) {
    $.utils.setText(3, value, this);
  }
  toString(): string { return "BicturePayload_" + super.toString(); }
}
export class SpendPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "SpendPayload",
    id: "9e18059a55e07db8",
    size: new $.ObjectSize(0, 1),
  };
  get spendEventId(): string {
    return $.utils.getText(0, this);
  }
  set spendEventId(value: string) {
    $.utils.setText(0, value, this);
  }
  toString(): string { return "SpendPayload_" + super.toString(); }
}
export class MessageReceivedPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "MessageReceivedPayload",
    id: "f88d58ca3ff252a3",
    size: new $.ObjectSize(0, 8),
  };
  get messageId(): string {
    return $.utils.getText(0, this);
  }
  set messageId(value: string) {
    $.utils.setText(0, value, this);
  }
  get channelId(): string {
    return $.utils.getText(1, this);
  }
  set channelId(value: string) {
    $.utils.setText(1, value, this);
  }
  get botUserId(): string {
    return $.utils.getText(2, this);
  }
  set botUserId(value: string) {
    $.utils.setText(2, value, this);
  }
  get content(): string {
    return $.utils.getText(3, this);
  }
  set content(value: string) {
    $.utils.setText(3, value, this);
  }
  _adoptMentionUserIds(value: $.Orphan<$.List<string>>): void {
    $.utils.adopt(value, $.utils.getPointer(4, this));
  }
  _disownMentionUserIds(): $.Orphan<$.List<string>> {
    return $.utils.disown(this.mentionUserIds);
  }
  get mentionUserIds(): $.List<string> {
    return $.utils.getList(4, $.TextList, this);
  }
  _hasMentionUserIds(): boolean {
    return !$.utils.isNull($.utils.getPointer(4, this));
  }
  _initMentionUserIds(length: number): $.List<string> {
    return $.utils.initList(4, $.TextList, length, this);
  }
  set mentionUserIds(value: $.List<string>) {
    $.utils.copyFrom(value, $.utils.getPointer(4, this));
  }
  _adoptMentionRoleIds(value: $.Orphan<$.List<string>>): void {
    $.utils.adopt(value, $.utils.getPointer(5, this));
  }
  _disownMentionRoleIds(): $.Orphan<$.List<string>> {
    return $.utils.disown(this.mentionRoleIds);
  }
  get mentionRoleIds(): $.List<string> {
    return $.utils.getList(5, $.TextList, this);
  }
  _hasMentionRoleIds(): boolean {
    return !$.utils.isNull($.utils.getPointer(5, this));
  }
  _initMentionRoleIds(length: number): $.List<string> {
    return $.utils.initList(5, $.TextList, length, this);
  }
  set mentionRoleIds(value: $.List<string>) {
    $.utils.copyFrom(value, $.utils.getPointer(5, this));
  }
  get replyMessageId(): string {
    return $.utils.getText(6, this);
  }
  set replyMessageId(value: string) {
    $.utils.setText(6, value, this);
  }
  get replyChannelId(): string {
    return $.utils.getText(7, this);
  }
  set replyChannelId(value: string) {
    $.utils.setText(7, value, this);
  }
  toString(): string { return "MessageReceivedPayload_" + super.toString(); }
}
export class ChannelMessagePayload extends $.Struct {
  static readonly _capnp = {
    displayName: "ChannelMessagePayload",
    id: "d949edd25bc563a2",
    size: new $.ObjectSize(0, 2),
  };
  get channelId(): string {
    return $.utils.getText(0, this);
  }
  set channelId(value: string) {
    $.utils.setText(0, value, this);
  }
  get content(): string {
    return $.utils.getText(1, this);
  }
  set content(value: string) {
    $.utils.setText(1, value, this);
  }
  toString(): string { return "ChannelMessagePayload_" + super.toString(); }
}
export class InteractionEditPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "InteractionEditPayload",
    id: "931ede4bd09855b5",
    size: new $.ObjectSize(0, 3),
  };
  get applicationId(): string {
    return $.utils.getText(0, this);
  }
  set applicationId(value: string) {
    $.utils.setText(0, value, this);
  }
  get interactionToken(): string {
    return $.utils.getText(1, this);
  }
  set interactionToken(value: string) {
    $.utils.setText(1, value, this);
  }
  get content(): string {
    return $.utils.getText(2, this);
  }
  set content(value: string) {
    $.utils.setText(2, value, this);
  }
  toString(): string { return "InteractionEditPayload_" + super.toString(); }
}
/**
* One slash-command option as a name/value pair. Values are carried as Text;
* the command layer coerces them exactly as it does Discord option values.
*
*/
export class DevProxyCommandOption extends $.Struct {
  static readonly _capnp = {
    displayName: "DevProxyCommandOption",
    id: "8039fbbed6348728",
    size: new $.ObjectSize(0, 2),
  };
  get name(): string {
    return $.utils.getText(0, this);
  }
  set name(value: string) {
    $.utils.setText(0, value, this);
  }
  get value(): string {
    return $.utils.getText(1, this);
  }
  set value(value: string) {
    $.utils.setText(1, value, this);
  }
  toString(): string { return "DevProxyCommandOption_" + super.toString(); }
}
/**
* A command invocation proxied by the dev-proxy worker on behalf of a
* Cloudflare Access + DPoP browser session. The gateway's DevProxy entrypoint
* reconstructs a synthetic Discord interaction from this and runs the SAME
* command pre-flight (Cedar command.* + limits + bans) a real interaction
* would. `command` is the slash-command name (e.g. "ask"); subjectUserId is
* the Discord user the command is authorized as.
*
*/
export class DevProxyCommandPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "DevProxyCommandPayload",
    id: "f26c75595c0b9716",
    size: new $.ObjectSize(0, 8),
  };
  static _Options: $.ListCtor<DevProxyCommandOption>;
  get command(): string {
    return $.utils.getText(0, this);
  }
  set command(value: string) {
    $.utils.setText(0, value, this);
  }
  get guildId(): string {
    return $.utils.getText(1, this);
  }
  set guildId(value: string) {
    $.utils.setText(1, value, this);
  }
  get channelId(): string {
    return $.utils.getText(2, this);
  }
  set channelId(value: string) {
    $.utils.setText(2, value, this);
  }
  get subjectUserId(): string {
    return $.utils.getText(3, this);
  }
  set subjectUserId(value: string) {
    $.utils.setText(3, value, this);
  }
  get subjectUsername(): string {
    return $.utils.getText(4, this);
  }
  set subjectUsername(value: string) {
    $.utils.setText(4, value, this);
  }
  get applicationId(): string {
    return $.utils.getText(5, this);
  }
  set applicationId(value: string) {
    $.utils.setText(5, value, this);
  }
  get interactionToken(): string {
    return $.utils.getText(6, this);
  }
  set interactionToken(value: string) {
    $.utils.setText(6, value, this);
  }
  _adoptOptions(value: $.Orphan<$.List<DevProxyCommandOption>>): void {
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownOptions(): $.Orphan<$.List<DevProxyCommandOption>> {
    return $.utils.disown(this.options);
  }
  get options(): $.List<DevProxyCommandOption> {
    return $.utils.getList(7, DevProxyCommandPayload._Options, this);
  }
  _hasOptions(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initOptions(length: number): $.List<DevProxyCommandOption> {
    return $.utils.initList(7, DevProxyCommandPayload._Options, length, this);
  }
  set options(value: $.List<DevProxyCommandOption>) {
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  toString(): string { return "DevProxyCommandPayload_" + super.toString(); }
}
export class EventEnvelope_Actor extends $.Struct {
  static readonly _capnp = {
    displayName: "actor",
    id: "ca483fdaf194ca92",
    size: new $.ObjectSize(8, 8),
  };
  get userId(): string {
    return $.utils.getText(4, this);
  }
  set userId(value: string) {
    $.utils.setText(4, value, this);
  }
  get username(): string {
    return $.utils.getText(5, this);
  }
  set username(value: string) {
    $.utils.setText(5, value, this);
  }
  toString(): string { return "EventEnvelope_Actor_" + super.toString(); }
}
export const EventEnvelope_Payload_Which = {
  THREAD_START: 0,
  THREAD_REPLY: 1,
  CHANNEL_REPLY: 2,
  RAGJAM: 3,
  SPEND: 4,
  ASK: 5,
  BICTURE: 6,
  REPLY_CHANNEL_MESSAGE: 7,
  REPLY_INTERACTION_EDIT: 8,
  MESSAGE_RECEIVED: 9,
  DEVPROXY_COMMAND: 10
} as const;
export type EventEnvelope_Payload_Which = (typeof EventEnvelope_Payload_Which)[keyof typeof EventEnvelope_Payload_Which];
export class EventEnvelope_Payload extends $.Struct {
  static readonly THREAD_START = EventEnvelope_Payload_Which.THREAD_START;
  static readonly THREAD_REPLY = EventEnvelope_Payload_Which.THREAD_REPLY;
  static readonly CHANNEL_REPLY = EventEnvelope_Payload_Which.CHANNEL_REPLY;
  static readonly RAGJAM = EventEnvelope_Payload_Which.RAGJAM;
  static readonly SPEND = EventEnvelope_Payload_Which.SPEND;
  static readonly ASK = EventEnvelope_Payload_Which.ASK;
  static readonly BICTURE = EventEnvelope_Payload_Which.BICTURE;
  static readonly REPLY_CHANNEL_MESSAGE = EventEnvelope_Payload_Which.REPLY_CHANNEL_MESSAGE;
  static readonly REPLY_INTERACTION_EDIT = EventEnvelope_Payload_Which.REPLY_INTERACTION_EDIT;
  static readonly MESSAGE_RECEIVED = EventEnvelope_Payload_Which.MESSAGE_RECEIVED;
  static readonly DEVPROXY_COMMAND = EventEnvelope_Payload_Which.DEVPROXY_COMMAND;
  static readonly _capnp = {
    displayName: "payload",
    id: "a636c8f1ec42d04d",
    size: new $.ObjectSize(8, 8),
  };
  _adoptThreadStart(value: $.Orphan<ChatPayload>): void {
    $.utils.setUint16(2, 0, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownThreadStart(): $.Orphan<ChatPayload> {
    return $.utils.disown(this.threadStart);
  }
  get threadStart(): ChatPayload {
    $.utils.testWhich("threadStart", $.utils.getUint16(2, this), 0, this);
    return $.utils.getStruct(7, ChatPayload, this);
  }
  _hasThreadStart(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initThreadStart(): ChatPayload {
    $.utils.setUint16(2, 0, this);
    return $.utils.initStructAt(7, ChatPayload, this);
  }
  get _isThreadStart(): boolean {
    return $.utils.getUint16(2, this) === 0;
  }
  set threadStart(value: ChatPayload) {
    $.utils.setUint16(2, 0, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptThreadReply(value: $.Orphan<ChatPayload>): void {
    $.utils.setUint16(2, 1, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownThreadReply(): $.Orphan<ChatPayload> {
    return $.utils.disown(this.threadReply);
  }
  get threadReply(): ChatPayload {
    $.utils.testWhich("threadReply", $.utils.getUint16(2, this), 1, this);
    return $.utils.getStruct(7, ChatPayload, this);
  }
  _hasThreadReply(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initThreadReply(): ChatPayload {
    $.utils.setUint16(2, 1, this);
    return $.utils.initStructAt(7, ChatPayload, this);
  }
  get _isThreadReply(): boolean {
    return $.utils.getUint16(2, this) === 1;
  }
  set threadReply(value: ChatPayload) {
    $.utils.setUint16(2, 1, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptChannelReply(value: $.Orphan<ChatPayload>): void {
    $.utils.setUint16(2, 2, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownChannelReply(): $.Orphan<ChatPayload> {
    return $.utils.disown(this.channelReply);
  }
  get channelReply(): ChatPayload {
    $.utils.testWhich("channelReply", $.utils.getUint16(2, this), 2, this);
    return $.utils.getStruct(7, ChatPayload, this);
  }
  _hasChannelReply(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initChannelReply(): ChatPayload {
    $.utils.setUint16(2, 2, this);
    return $.utils.initStructAt(7, ChatPayload, this);
  }
  get _isChannelReply(): boolean {
    return $.utils.getUint16(2, this) === 2;
  }
  set channelReply(value: ChatPayload) {
    $.utils.setUint16(2, 2, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptRagjam(value: $.Orphan<RagjamPayload>): void {
    $.utils.setUint16(2, 3, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownRagjam(): $.Orphan<RagjamPayload> {
    return $.utils.disown(this.ragjam);
  }
  get ragjam(): RagjamPayload {
    $.utils.testWhich("ragjam", $.utils.getUint16(2, this), 3, this);
    return $.utils.getStruct(7, RagjamPayload, this);
  }
  _hasRagjam(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initRagjam(): RagjamPayload {
    $.utils.setUint16(2, 3, this);
    return $.utils.initStructAt(7, RagjamPayload, this);
  }
  get _isRagjam(): boolean {
    return $.utils.getUint16(2, this) === 3;
  }
  set ragjam(value: RagjamPayload) {
    $.utils.setUint16(2, 3, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptSpend(value: $.Orphan<SpendPayload>): void {
    $.utils.setUint16(2, 4, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownSpend(): $.Orphan<SpendPayload> {
    return $.utils.disown(this.spend);
  }
  get spend(): SpendPayload {
    $.utils.testWhich("spend", $.utils.getUint16(2, this), 4, this);
    return $.utils.getStruct(7, SpendPayload, this);
  }
  _hasSpend(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initSpend(): SpendPayload {
    $.utils.setUint16(2, 4, this);
    return $.utils.initStructAt(7, SpendPayload, this);
  }
  get _isSpend(): boolean {
    return $.utils.getUint16(2, this) === 4;
  }
  set spend(value: SpendPayload) {
    $.utils.setUint16(2, 4, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptAsk(value: $.Orphan<ChatPayload>): void {
    $.utils.setUint16(2, 5, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownAsk(): $.Orphan<ChatPayload> {
    return $.utils.disown(this.ask);
  }
  get ask(): ChatPayload {
    $.utils.testWhich("ask", $.utils.getUint16(2, this), 5, this);
    return $.utils.getStruct(7, ChatPayload, this);
  }
  _hasAsk(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initAsk(): ChatPayload {
    $.utils.setUint16(2, 5, this);
    return $.utils.initStructAt(7, ChatPayload, this);
  }
  get _isAsk(): boolean {
    return $.utils.getUint16(2, this) === 5;
  }
  set ask(value: ChatPayload) {
    $.utils.setUint16(2, 5, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptBicture(value: $.Orphan<BicturePayload>): void {
    $.utils.setUint16(2, 6, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownBicture(): $.Orphan<BicturePayload> {
    return $.utils.disown(this.bicture);
  }
  get bicture(): BicturePayload {
    $.utils.testWhich("bicture", $.utils.getUint16(2, this), 6, this);
    return $.utils.getStruct(7, BicturePayload, this);
  }
  _hasBicture(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initBicture(): BicturePayload {
    $.utils.setUint16(2, 6, this);
    return $.utils.initStructAt(7, BicturePayload, this);
  }
  get _isBicture(): boolean {
    return $.utils.getUint16(2, this) === 6;
  }
  set bicture(value: BicturePayload) {
    $.utils.setUint16(2, 6, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptReplyChannelMessage(value: $.Orphan<ChannelMessagePayload>): void {
    $.utils.setUint16(2, 7, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownReplyChannelMessage(): $.Orphan<ChannelMessagePayload> {
    return $.utils.disown(this.replyChannelMessage);
  }
  get replyChannelMessage(): ChannelMessagePayload {
    $.utils.testWhich("replyChannelMessage", $.utils.getUint16(2, this), 7, this);
    return $.utils.getStruct(7, ChannelMessagePayload, this);
  }
  _hasReplyChannelMessage(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initReplyChannelMessage(): ChannelMessagePayload {
    $.utils.setUint16(2, 7, this);
    return $.utils.initStructAt(7, ChannelMessagePayload, this);
  }
  get _isReplyChannelMessage(): boolean {
    return $.utils.getUint16(2, this) === 7;
  }
  set replyChannelMessage(value: ChannelMessagePayload) {
    $.utils.setUint16(2, 7, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptReplyInteractionEdit(value: $.Orphan<InteractionEditPayload>): void {
    $.utils.setUint16(2, 8, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownReplyInteractionEdit(): $.Orphan<InteractionEditPayload> {
    return $.utils.disown(this.replyInteractionEdit);
  }
  get replyInteractionEdit(): InteractionEditPayload {
    $.utils.testWhich("replyInteractionEdit", $.utils.getUint16(2, this), 8, this);
    return $.utils.getStruct(7, InteractionEditPayload, this);
  }
  _hasReplyInteractionEdit(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initReplyInteractionEdit(): InteractionEditPayload {
    $.utils.setUint16(2, 8, this);
    return $.utils.initStructAt(7, InteractionEditPayload, this);
  }
  get _isReplyInteractionEdit(): boolean {
    return $.utils.getUint16(2, this) === 8;
  }
  set replyInteractionEdit(value: InteractionEditPayload) {
    $.utils.setUint16(2, 8, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptMessageReceived(value: $.Orphan<MessageReceivedPayload>): void {
    $.utils.setUint16(2, 9, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownMessageReceived(): $.Orphan<MessageReceivedPayload> {
    return $.utils.disown(this.messageReceived);
  }
  get messageReceived(): MessageReceivedPayload {
    $.utils.testWhich("messageReceived", $.utils.getUint16(2, this), 9, this);
    return $.utils.getStruct(7, MessageReceivedPayload, this);
  }
  _hasMessageReceived(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initMessageReceived(): MessageReceivedPayload {
    $.utils.setUint16(2, 9, this);
    return $.utils.initStructAt(7, MessageReceivedPayload, this);
  }
  get _isMessageReceived(): boolean {
    return $.utils.getUint16(2, this) === 9;
  }
  set messageReceived(value: MessageReceivedPayload) {
    $.utils.setUint16(2, 9, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptDevproxyCommand(value: $.Orphan<DevProxyCommandPayload>): void {
    $.utils.setUint16(2, 10, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownDevproxyCommand(): $.Orphan<DevProxyCommandPayload> {
    return $.utils.disown(this.devproxyCommand);
  }
  get devproxyCommand(): DevProxyCommandPayload {
    $.utils.testWhich("devproxyCommand", $.utils.getUint16(2, this), 10, this);
    return $.utils.getStruct(7, DevProxyCommandPayload, this);
  }
  _hasDevproxyCommand(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initDevproxyCommand(): DevProxyCommandPayload {
    $.utils.setUint16(2, 10, this);
    return $.utils.initStructAt(7, DevProxyCommandPayload, this);
  }
  get _isDevproxyCommand(): boolean {
    return $.utils.getUint16(2, this) === 10;
  }
  set devproxyCommand(value: DevProxyCommandPayload) {
    $.utils.setUint16(2, 10, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  toString(): string { return "EventEnvelope_Payload_" + super.toString(); }
  which(): EventEnvelope_Payload_Which {
    return $.utils.getUint16(2, this) as EventEnvelope_Payload_Which;
  }
}
export class EventEnvelope extends $.Struct {
  static readonly _capnp = {
    displayName: "EventEnvelope",
    id: "ea799f50bc6beec6",
    size: new $.ObjectSize(8, 8),
  };
  get v(): number {
    return $.utils.getUint16(0, this);
  }
  set v(value: number) {
    $.utils.setUint16(0, value, this);
  }
  get type(): string {
    return $.utils.getText(0, this);
  }
  set type(value: string) {
    $.utils.setText(0, value, this);
  }
  get id(): string {
    return $.utils.getText(1, this);
  }
  set id(value: string) {
    $.utils.setText(1, value, this);
  }
  get occurredAt(): string {
    return $.utils.getText(2, this);
  }
  set occurredAt(value: string) {
    $.utils.setText(2, value, this);
  }
  get source(): string {
    return $.utils.getText(3, this);
  }
  set source(value: string) {
    $.utils.setText(3, value, this);
  }
  get actor(): EventEnvelope_Actor {
    return $.utils.getAs(EventEnvelope_Actor, this);
  }
  _initActor(): EventEnvelope_Actor {
    return $.utils.getAs(EventEnvelope_Actor, this);
  }
  get guildId(): string {
    return $.utils.getText(6, this);
  }
  set guildId(value: string) {
    $.utils.setText(6, value, this);
  }
  get payload(): EventEnvelope_Payload {
    return $.utils.getAs(EventEnvelope_Payload, this);
  }
  _initPayload(): EventEnvelope_Payload {
    return $.utils.getAs(EventEnvelope_Payload, this);
  }
  toString(): string { return "EventEnvelope_" + super.toString(); }
}
DevProxyCommandPayload._Options = $.CompositeList(DevProxyCommandOption);
