// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0x84bf4a759a05daf3n;
/**
* thread_start / thread_reply / channel_reply / ask jobs.
*
*/
export class ChatPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "ChatPayload",
    id: "a184a57b4d766c6d",
    size: new $.ObjectSize(0, 6),
  };
  get channelId(): string {
    return $.utils.getText(0, this);
  }
  set channelId(value: string) {
    $.utils.setText(0, value, this);
  }
  get messageId(): string {
    return $.utils.getText(1, this);
  }
  set messageId(value: string) {
    $.utils.setText(1, value, this);
  }
  get botUserId(): string {
    return $.utils.getText(2, this);
  }
  set botUserId(value: string) {
    $.utils.setText(2, value, this);
  }
  get prompt(): string {
    return $.utils.getText(3, this);
  }
  set prompt(value: string) {
    $.utils.setText(3, value, this);
  }
  get replyMessageId(): string {
    return $.utils.getText(4, this);
  }
  set replyMessageId(value: string) {
    $.utils.setText(4, value, this);
  }
  get replyChannelId(): string {
    return $.utils.getText(5, this);
  }
  set replyChannelId(value: string) {
    $.utils.setText(5, value, this);
  }
  toString(): string { return "ChatPayload_" + super.toString(); }
}
export class RagjamPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "RagjamPayload",
    id: "dfa667e5158a519b",
    size: new $.ObjectSize(0, 5),
  };
  get applicationId(): string {
    return $.utils.getText(0, this);
  }
  set applicationId(value: string) {
    $.utils.setText(0, value, this);
  }
  get interactionToken(): string {
    return $.utils.getText(1, this);
  }
  set interactionToken(value: string) {
    $.utils.setText(1, value, this);
  }
  get channelId(): string {
    return $.utils.getText(2, this);
  }
  set channelId(value: string) {
    $.utils.setText(2, value, this);
  }
  get prompt(): string {
    return $.utils.getText(3, this);
  }
  set prompt(value: string) {
    $.utils.setText(3, value, this);
  }
  get lyrics(): string {
    return $.utils.getText(4, this);
  }
  set lyrics(value: string) {
    $.utils.setText(4, value, this);
  }
  toString(): string { return "RagjamPayload_" + super.toString(); }
}
export class BicturePayload extends $.Struct {
  static readonly _capnp = {
    displayName: "BicturePayload",
    id: "cdea29560f4b3187",
    size: new $.ObjectSize(0, 4),
  };
  get applicationId(): string {
    return $.utils.getText(0, this);
  }
  set applicationId(value: string) {
    $.utils.setText(0, value, this);
  }
  get interactionToken(): string {
    return $.utils.getText(1, this);
  }
  set interactionToken(value: string) {
    $.utils.setText(1, value, this);
  }
  get channelId(): string {
    return $.utils.getText(2, this);
  }
  set channelId(value: string) {
    $.utils.setText(2, value, this);
  }
  get prompt(): string {
    return $.utils.getText(3, this);
  }
  set prompt(value: string) {
    $.utils.setText(3, value, this);
  }
  toString(): string { return "BicturePayload_" + super.toString(); }
}
export class SpendPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "SpendPayload",
    id: "9e18059a55e07db8",
    size: new $.ObjectSize(0, 1),
  };
  get spendEventId(): string {
    return $.utils.getText(0, this);
  }
  set spendEventId(value: string) {
    $.utils.setText(0, value, this);
  }
  toString(): string { return "SpendPayload_" + super.toString(); }
}
export class MessageReceivedPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "MessageReceivedPayload",
    id: "f88d58ca3ff252a3",
    size: new $.ObjectSize(0, 8),
  };
  get messageId(): string {
    return $.utils.getText(0, this);
  }
  set messageId(value: string) {
    $.utils.setText(0, value, this);
  }
  get channelId(): string {
    return $.utils.getText(1, this);
  }
  set channelId(value: string) {
    $.utils.setText(1, value, this);
  }
  get botUserId(): string {
    return $.utils.getText(2, this);
  }
  set botUserId(value: string) {
    $.utils.setText(2, value, this);
  }
  get content(): string {
    return $.utils.getText(3, this);
  }
  set content(value: string) {
    $.utils.setText(3, value, this);
  }
  _adoptMentionUserIds(value: $.Orphan<$.List<string>>): void {
    $.utils.adopt(value, $.utils.getPointer(4, this));
  }
  _disownMentionUserIds(): $.Orphan<$.List<string>> {
    return $.utils.disown(this.mentionUserIds);
  }
  get mentionUserIds(): $.List<string> {
    return $.utils.getList(4, $.TextList, this);
  }
  _hasMentionUserIds(): boolean {
    return !$.utils.isNull($.utils.getPointer(4, this));
  }
  _initMentionUserIds(length: number): $.List<string> {
    return $.utils.initList(4, $.TextList, length, this);
  }
  set mentionUserIds(value: $.List<string>) {
    $.utils.copyFrom(value, $.utils.getPointer(4, this));
  }
  _adoptMentionRoleIds(value: $.Orphan<$.List<string>>): void {
    $.utils.adopt(value, $.utils.getPointer(5, this));
  }
  _disownMentionRoleIds(): $.Orphan<$.List<string>> {
    return $.utils.disown(this.mentionRoleIds);
  }
  get mentionRoleIds(): $.List<string> {
    return $.utils.getList(5, $.TextList, this);
  }
  _hasMentionRoleIds(): boolean {
    return !$.utils.isNull($.utils.getPointer(5, this));
  }
  _initMentionRoleIds(length: number): $.List<string> {
    return $.utils.initList(5, $.TextList, length, this);
  }
  set mentionRoleIds(value: $.List<string>) {
    $.utils.copyFrom(value, $.utils.getPointer(5, this));
  }
  get replyMessageId(): string {
    return $.utils.getText(6, this);
  }
  set replyMessageId(value: string) {
    $.utils.setText(6, value, this);
  }
  get replyChannelId(): string {
    return $.utils.getText(7, this);
  }
  set replyChannelId(value: string) {
    $.utils.setText(7, value, this);
  }
  toString(): string { return "MessageReceivedPayload_" + super.toString(); }
}
export class ChannelMessagePayload extends $.Struct {
  static readonly _capnp = {
    displayName: "ChannelMessagePayload",
    id: "d949edd25bc563a2",
    size: new $.ObjectSize(0, 2),
  };
  get channelId(): string {
    return $.utils.getText(0, this);
  }
  set channelId(value: string) {
    $.utils.setText(0, value, this);
  }
  get content(): string {
    return $.utils.getText(1, this);
  }
  set content(value: string) {
    $.utils.setText(1, value, this);
  }
  toString(): string { return "ChannelMessagePayload_" + super.toString(); }
}
export class InteractionEditPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "InteractionEditPayload",
    id: "931ede4bd09855b5",
    size: new $.ObjectSize(0, 3),
  };
  get applicationId(): string {
    return $.utils.getText(0, this);
  }
  set applicationId(value: string) {
    $.utils.setText(0, value, this);
  }
  get interactionToken(): string {
    return $.utils.getText(1, this);
  }
  set interactionToken(value: string) {
    $.utils.setText(1, value, this);
  }
  get content(): string {
    return $.utils.getText(2, this);
  }
  set content(value: string) {
    $.utils.setText(2, value, this);
  }
  toString(): string { return "InteractionEditPayload_" + super.toString(); }
}
/**
* One slash-command option as a name/value pair. Values are carried as Text;
* the command layer coerces them exactly as it does Discord option values.
*
*/
export class DevProxyCommandOption extends $.Struct {
  static readonly _capnp = {
    displayName: "DevProxyCommandOption",
    id: "8039fbbed6348728",
    size: new $.ObjectSize(0, 2),
  };
  get name(): string {
    return $.utils.getText(0, this);
  }
  set name(value: string) {
    $.utils.setText(0, value, this);
  }
  get value(): string {
    return $.utils.getText(1, this);
  }
  set value(value: string) {
    $.utils.setText(1, value, this);
  }
  toString(): string { return "DevProxyCommandOption_" + super.toString(); }
}
/**
* A command invocation proxied by the dev-proxy worker on behalf of a
* Cloudflare Access + Better Auth (Discord) browser session. The gateway's DevProxy entrypoint
* reconstructs a synthetic Discord interaction from this and runs the SAME
* command pre-flight (Cedar command.* + limits + bans) a real interaction
* would. `command` is the slash-command name (e.g. "ask"); subjectUserId is
* the Discord user the command is authorized as.
*
*/
export class DevProxyCommandPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "DevProxyCommandPayload",
    id: "f26c75595c0b9716",
    size: new $.ObjectSize(0, 8),
  };
  static _Options: $.ListCtor<DevProxyCommandOption>;
  get command(): string {
    return $.utils.getText(0, this);
  }
  set command(value: string) {
    $.utils.setText(0, value, this);
  }
  get guildId(): string {
    return $.utils.getText(1, this);
  }
  set guildId(value: string) {
    $.utils.setText(1, value, this);
  }
  get channelId(): string {
    return $.utils.getText(2, this);
  }
  set channelId(value: string) {
    $.utils.setText(2, value, this);
  }
  get subjectUserId(): string {
    return $.utils.getText(3, this);
  }
  set subjectUserId(value: string) {
    $.utils.setText(3, value, this);
  }
  get subjectUsername(): string {
    return $.utils.getText(4, this);
  }
  set subjectUsername(value: string) {
    $.utils.setText(4, value, this);
  }
  get applicationId(): string {
    return $.utils.getText(5, this);
  }
  set applicationId(value: string) {
    $.utils.setText(5, value, this);
  }
  get interactionToken(): string {
    return $.utils.getText(6, this);
  }
  set interactionToken(value: string) {
    $.utils.setText(6, value, this);
  }
  _adoptOptions(value: $.Orphan<$.List<DevProxyCommandOption>>): void {
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownOptions(): $.Orphan<$.List<DevProxyCommandOption>> {
    return $.utils.disown(this.options);
  }
  get options(): $.List<DevProxyCommandOption> {
    return $.utils.getList(7, DevProxyCommandPayload._Options, this);
  }
  _hasOptions(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initOptions(length: number): $.List<DevProxyCommandOption> {
    return $.utils.initList(7, DevProxyCommandPayload._Options, length, this);
  }
  set options(value: $.List<DevProxyCommandOption>) {
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  toString(): string { return "DevProxyCommandPayload_" + super.toString(); }
}
/**
* A single operation against the credential broker (workers/services/connectors).
* The uniform phantom-token model: `grant` exchanges the caller's authenticated
* identity for an opaque handle (the real credential is prepared server-side and
* never returned); `fetch`/`token`/`introspect` present that handle to use the
* credential without ever receiving it. `operation` names which; `connectorId`
* is set on `grant`/`begin_authorization`/`complete_authorization`; `handle` is
* set on the handle-bearing operations. Operation-specific parameters (the
* request for fetch, the code/state for a 3LO completion, installationId for a
* github_app grant) ride as JSON in `paramsJson` so a new connector kind needs
* no schema change — exactly as the identity token rides as an opaque JWS Text.
*
*/
export class ConnectorInvokePayload extends $.Struct {
  static readonly _capnp = {
    displayName: "ConnectorInvokePayload",
    id: "cb1e798561d75b89",
    size: new $.ObjectSize(0, 6),
  };
  get operation(): string {
    return $.utils.getText(0, this);
  }
  set operation(value: string) {
    $.utils.setText(0, value, this);
  }
  get connectorId(): string {
    return $.utils.getText(1, this);
  }
  set connectorId(value: string) {
    $.utils.setText(1, value, this);
  }
  get handle(): string {
    return $.utils.getText(2, this);
  }
  set handle(value: string) {
    $.utils.setText(2, value, this);
  }
  get subject(): string {
    return $.utils.getText(3, this);
  }
  set subject(value: string) {
    $.utils.setText(3, value, this);
  }
  _adoptScopes(value: $.Orphan<$.List<string>>): void {
    $.utils.adopt(value, $.utils.getPointer(4, this));
  }
  _disownScopes(): $.Orphan<$.List<string>> {
    return $.utils.disown(this.scopes);
  }
  get scopes(): $.List<string> {
    return $.utils.getList(4, $.TextList, this);
  }
  _hasScopes(): boolean {
    return !$.utils.isNull($.utils.getPointer(4, this));
  }
  _initScopes(length: number): $.List<string> {
    return $.utils.initList(4, $.TextList, length, this);
  }
  set scopes(value: $.List<string>) {
    $.utils.copyFrom(value, $.utils.getPointer(4, this));
  }
  get paramsJson(): string {
    return $.utils.getText(5, this);
  }
  set paramsJson(value: string) {
    $.utils.setText(5, value, this);
  }
  toString(): string { return "ConnectorInvokePayload_" + super.toString(); }
}
/**
* A verified third-party webhook delivery, enqueued by the webhooks edge
* worker (webhooks.jsmunro.me) AFTER the broker's webhook_verify confirmed the
* provider signature over the exact body bytes. `connectorId` names the
* connector whose secret verified it; `provider` is the signature scheme
* ("github"/"stripe"); `eventId` is the broker-returned provider event id
* (GitHub's X-GitHub-Delivery, Stripe's body id) — present only when the
* provider sent one; `eventType` is the provider's event name (e.g. GitHub's
* X-GitHub-Event) when one travels in a header; `receivedAt` is the edge
* receipt time (ISO 8601). The body rides base64 because the signature was
* computed over exact bytes and the workflows worker may need to re-derive facts from
* the same bytes.
*
*/
export class WebhookEventPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "WebhookEventPayload",
    id: "da02b4842df55cbf",
    size: new $.ObjectSize(0, 6),
  };
  get connectorId(): string {
    return $.utils.getText(0, this);
  }
  set connectorId(value: string) {
    $.utils.setText(0, value, this);
  }
  get provider(): string {
    return $.utils.getText(1, this);
  }
  set provider(value: string) {
    $.utils.setText(1, value, this);
  }
  get eventId(): string {
    return $.utils.getText(2, this);
  }
  set eventId(value: string) {
    $.utils.setText(2, value, this);
  }
  get eventType(): string {
    return $.utils.getText(3, this);
  }
  set eventType(value: string) {
    $.utils.setText(3, value, this);
  }
  get receivedAt(): string {
    return $.utils.getText(4, this);
  }
  set receivedAt(value: string) {
    $.utils.setText(4, value, this);
  }
  get bodyBase64(): string {
    return $.utils.getText(5, this);
  }
  set bodyBase64(value: string) {
    $.utils.setText(5, value, this);
  }
  toString(): string { return "WebhookEventPayload_" + super.toString(); }
}
/**
* Generic application -> egress request. The caller signs this envelope with
* its service identity; `profile` selects the egress worker's local policy
* and credential injector. `headersJson` is a JSON object of caller-supplied
* safe headers. The optional body travels as a sibling RPC argument, and
* `bodySha256` binds those bytes to the signed envelope.
*
*/
export class EgressRequestPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "EgressRequestPayload",
    id: "b243ccfd7f319c91",
    size: new $.ObjectSize(0, 5),
  };
  get profile(): string {
    return $.utils.getText(0, this);
  }
  set profile(value: string) {
    $.utils.setText(0, value, this);
  }
  get method(): string {
    return $.utils.getText(1, this);
  }
  set method(value: string) {
    $.utils.setText(1, value, this);
  }
  get url(): string {
    return $.utils.getText(2, this);
  }
  set url(value: string) {
    $.utils.setText(2, value, this);
  }
  get headersJson(): string {
    return $.utils.getText(3, this);
  }
  set headersJson(value: string) {
    $.utils.setText(3, value, this);
  }
  get bodySha256(): string {
    return $.utils.getText(4, this);
  }
  set bodySha256(value: string) {
    $.utils.setText(4, value, this);
  }
  toString(): string { return "EgressRequestPayload_" + super.toString(); }
}
/**
* Generic generated-app request. Middleware clients validate app-facing HTTP
* routes, the gateway signs this envelope, and a generated application service
* server verifies the service boundary before dispatching to app code.
*
*/
export class ApplicationRequestPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "ApplicationRequestPayload",
    id: "ebe9cf2930a67241",
    size: new $.ObjectSize(0, 8),
  };
  get applicationId(): string {
    return $.utils.getText(0, this);
  }
  set applicationId(value: string) {
    $.utils.setText(0, value, this);
  }
  get operationId(): string {
    return $.utils.getText(1, this);
  }
  set operationId(value: string) {
    $.utils.setText(1, value, this);
  }
  get serviceOperation(): string {
    return $.utils.getText(2, this);
  }
  set serviceOperation(value: string) {
    $.utils.setText(2, value, this);
  }
  get method(): string {
    return $.utils.getText(3, this);
  }
  set method(value: string) {
    $.utils.setText(3, value, this);
  }
  get url(): string {
    return $.utils.getText(4, this);
  }
  set url(value: string) {
    $.utils.setText(4, value, this);
  }
  get headersJson(): string {
    return $.utils.getText(5, this);
  }
  set headersJson(value: string) {
    $.utils.setText(5, value, this);
  }
  get bodyBase64(): string {
    return $.utils.getText(6, this);
  }
  set bodyBase64(value: string) {
    $.utils.setText(6, value, this);
  }
  get linkedTokenSha256(): string {
    return $.utils.getText(7, this);
  }
  set linkedTokenSha256(value: string) {
    $.utils.setText(7, value, this);
  }
  toString(): string { return "ApplicationRequestPayload_" + super.toString(); }
}
/**
* One HTTP-shaped control-plane operation against registry.jsmunro.me,
* carried over the registry worker's own service-binding entrypoint. The
* middleware client owns browser authentication; the service server verifies
* the signed service hop, consumes request placement, runs Cedar service.invoke,
* then dispatches the operation named here.
*
*/
export class RegistryInvokePayload extends $.Struct {
  static readonly _capnp = {
    displayName: "RegistryInvokePayload",
    id: "f8f0768dbf188314",
    size: new $.ObjectSize(0, 4),
  };
  get operation(): string {
    return $.utils.getText(0, this);
  }
  set operation(value: string) {
    $.utils.setText(0, value, this);
  }
  get actorJson(): string {
    return $.utils.getText(1, this);
  }
  set actorJson(value: string) {
    $.utils.setText(1, value, this);
  }
  get bodyJson(): string {
    return $.utils.getText(2, this);
  }
  set bodyJson(value: string) {
    $.utils.setText(2, value, this);
  }
  get targetId(): string {
    return $.utils.getText(3, this);
  }
  set targetId(value: string) {
    $.utils.setText(3, value, this);
  }
  toString(): string { return "RegistryInvokePayload_" + super.toString(); }
}
/**
* One GraphQL metadata resolver request accepted by metadata.jsmunro.me's
* service server. The HTTP middleware authenticates the bearer token and
* validates the outer GraphQL request shape; the service boundary verifies the
* signed hop, placement, and Cedar service.invoke before executing resolvers.
*
*/
export class MetadataQueryPayload extends $.Struct {
  static readonly _capnp = {
    displayName: "MetadataQueryPayload",
    id: "966fe3592a0b21ab",
    size: new $.ObjectSize(0, 3),
  };
  get query(): string {
    return $.utils.getText(0, this);
  }
  set query(value: string) {
    $.utils.setText(0, value, this);
  }
  get variablesJson(): string {
    return $.utils.getText(1, this);
  }
  set variablesJson(value: string) {
    $.utils.setText(1, value, this);
  }
  get operationName(): string {
    return $.utils.getText(2, this);
  }
  set operationName(value: string) {
    $.utils.setText(2, value, this);
  }
  toString(): string { return "MetadataQueryPayload_" + super.toString(); }
}
/**
* One HTTP-shaped GitHub webhook delivery accepted by attest.jsmunro.me's own
* service-binding entrypoint. The middleware client owns the edge-level
* method/size checks and collects only the small filtered GitHub signature
* headers (x-hub-signature-256, x-github-delivery, x-github-event) into
* headersJson; the service server verifies the signed service hop, then
* verifies the GitHub signature via the connectors broker, dedupes, fetches
* the commit tree, and records the attestation.
*
*/
export class AttestInvokePayload extends $.Struct {
  static readonly _capnp = {
    displayName: "AttestInvokePayload",
    id: "37f05d09d1c91cee",
    size: new $.ObjectSize(0, 3),
  };
  get operation(): string {
    return $.utils.getText(0, this);
  }
  set operation(value: string) {
    $.utils.setText(0, value, this);
  }
  get headersJson(): string {
    return $.utils.getText(1, this);
  }
  set headersJson(value: string) {
    $.utils.setText(1, value, this);
  }
  get bodyBase64(): string {
    return $.utils.getText(2, this);
  }
  set bodyBase64(value: string) {
    $.utils.setText(2, value, this);
  }
  toString(): string { return "AttestInvokePayload_" + super.toString(); }
}
export class EventEnvelope_Actor extends $.Struct {
  static readonly _capnp = {
    displayName: "actor",
    id: "ca483fdaf194ca92",
    size: new $.ObjectSize(8, 8),
  };
  get userId(): string {
    return $.utils.getText(4, this);
  }
  set userId(value: string) {
    $.utils.setText(4, value, this);
  }
  get username(): string {
    return $.utils.getText(5, this);
  }
  set username(value: string) {
    $.utils.setText(5, value, this);
  }
  toString(): string { return "EventEnvelope_Actor_" + super.toString(); }
}
export const EventEnvelope_Payload_Which = {
  THREAD_START: 0,
  THREAD_REPLY: 1,
  CHANNEL_REPLY: 2,
  RAGJAM: 3,
  SPEND: 4,
  ASK: 5,
  BICTURE: 6,
  REPLY_CHANNEL_MESSAGE: 7,
  REPLY_INTERACTION_EDIT: 8,
  MESSAGE_RECEIVED: 9,
  DEVPROXY_COMMAND: 10,
  CONNECTOR_INVOKE: 11,
  WEBHOOK_EVENT: 12,
  EGRESS_REQUEST: 13,
  APPLICATION_REQUEST: 14,
  REGISTRY_INVOKE: 15,
  METADATA_QUERY: 16,
  ATTEST_INVOKE: 17
} as const;
export type EventEnvelope_Payload_Which = (typeof EventEnvelope_Payload_Which)[keyof typeof EventEnvelope_Payload_Which];
export class EventEnvelope_Payload extends $.Struct {
  static readonly THREAD_START = EventEnvelope_Payload_Which.THREAD_START;
  static readonly THREAD_REPLY = EventEnvelope_Payload_Which.THREAD_REPLY;
  static readonly CHANNEL_REPLY = EventEnvelope_Payload_Which.CHANNEL_REPLY;
  static readonly RAGJAM = EventEnvelope_Payload_Which.RAGJAM;
  static readonly SPEND = EventEnvelope_Payload_Which.SPEND;
  static readonly ASK = EventEnvelope_Payload_Which.ASK;
  static readonly BICTURE = EventEnvelope_Payload_Which.BICTURE;
  static readonly REPLY_CHANNEL_MESSAGE = EventEnvelope_Payload_Which.REPLY_CHANNEL_MESSAGE;
  static readonly REPLY_INTERACTION_EDIT = EventEnvelope_Payload_Which.REPLY_INTERACTION_EDIT;
  static readonly MESSAGE_RECEIVED = EventEnvelope_Payload_Which.MESSAGE_RECEIVED;
  static readonly DEVPROXY_COMMAND = EventEnvelope_Payload_Which.DEVPROXY_COMMAND;
  static readonly CONNECTOR_INVOKE = EventEnvelope_Payload_Which.CONNECTOR_INVOKE;
  static readonly WEBHOOK_EVENT = EventEnvelope_Payload_Which.WEBHOOK_EVENT;
  static readonly EGRESS_REQUEST = EventEnvelope_Payload_Which.EGRESS_REQUEST;
  static readonly APPLICATION_REQUEST = EventEnvelope_Payload_Which.APPLICATION_REQUEST;
  static readonly REGISTRY_INVOKE = EventEnvelope_Payload_Which.REGISTRY_INVOKE;
  static readonly METADATA_QUERY = EventEnvelope_Payload_Which.METADATA_QUERY;
  static readonly ATTEST_INVOKE = EventEnvelope_Payload_Which.ATTEST_INVOKE;
  static readonly _capnp = {
    displayName: "payload",
    id: "a636c8f1ec42d04d",
    size: new $.ObjectSize(8, 8),
  };
  _adoptThreadStart(value: $.Orphan<ChatPayload>): void {
    $.utils.setUint16(2, 0, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownThreadStart(): $.Orphan<ChatPayload> {
    return $.utils.disown(this.threadStart);
  }
  get threadStart(): ChatPayload {
    $.utils.testWhich("threadStart", $.utils.getUint16(2, this), 0, this);
    return $.utils.getStruct(7, ChatPayload, this);
  }
  _hasThreadStart(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initThreadStart(): ChatPayload {
    $.utils.setUint16(2, 0, this);
    return $.utils.initStructAt(7, ChatPayload, this);
  }
  get _isThreadStart(): boolean {
    return $.utils.getUint16(2, this) === 0;
  }
  set threadStart(value: ChatPayload) {
    $.utils.setUint16(2, 0, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptThreadReply(value: $.Orphan<ChatPayload>): void {
    $.utils.setUint16(2, 1, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownThreadReply(): $.Orphan<ChatPayload> {
    return $.utils.disown(this.threadReply);
  }
  get threadReply(): ChatPayload {
    $.utils.testWhich("threadReply", $.utils.getUint16(2, this), 1, this);
    return $.utils.getStruct(7, ChatPayload, this);
  }
  _hasThreadReply(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initThreadReply(): ChatPayload {
    $.utils.setUint16(2, 1, this);
    return $.utils.initStructAt(7, ChatPayload, this);
  }
  get _isThreadReply(): boolean {
    return $.utils.getUint16(2, this) === 1;
  }
  set threadReply(value: ChatPayload) {
    $.utils.setUint16(2, 1, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptChannelReply(value: $.Orphan<ChatPayload>): void {
    $.utils.setUint16(2, 2, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownChannelReply(): $.Orphan<ChatPayload> {
    return $.utils.disown(this.channelReply);
  }
  get channelReply(): ChatPayload {
    $.utils.testWhich("channelReply", $.utils.getUint16(2, this), 2, this);
    return $.utils.getStruct(7, ChatPayload, this);
  }
  _hasChannelReply(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initChannelReply(): ChatPayload {
    $.utils.setUint16(2, 2, this);
    return $.utils.initStructAt(7, ChatPayload, this);
  }
  get _isChannelReply(): boolean {
    return $.utils.getUint16(2, this) === 2;
  }
  set channelReply(value: ChatPayload) {
    $.utils.setUint16(2, 2, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptRagjam(value: $.Orphan<RagjamPayload>): void {
    $.utils.setUint16(2, 3, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownRagjam(): $.Orphan<RagjamPayload> {
    return $.utils.disown(this.ragjam);
  }
  get ragjam(): RagjamPayload {
    $.utils.testWhich("ragjam", $.utils.getUint16(2, this), 3, this);
    return $.utils.getStruct(7, RagjamPayload, this);
  }
  _hasRagjam(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initRagjam(): RagjamPayload {
    $.utils.setUint16(2, 3, this);
    return $.utils.initStructAt(7, RagjamPayload, this);
  }
  get _isRagjam(): boolean {
    return $.utils.getUint16(2, this) === 3;
  }
  set ragjam(value: RagjamPayload) {
    $.utils.setUint16(2, 3, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptSpend(value: $.Orphan<SpendPayload>): void {
    $.utils.setUint16(2, 4, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownSpend(): $.Orphan<SpendPayload> {
    return $.utils.disown(this.spend);
  }
  get spend(): SpendPayload {
    $.utils.testWhich("spend", $.utils.getUint16(2, this), 4, this);
    return $.utils.getStruct(7, SpendPayload, this);
  }
  _hasSpend(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initSpend(): SpendPayload {
    $.utils.setUint16(2, 4, this);
    return $.utils.initStructAt(7, SpendPayload, this);
  }
  get _isSpend(): boolean {
    return $.utils.getUint16(2, this) === 4;
  }
  set spend(value: SpendPayload) {
    $.utils.setUint16(2, 4, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptAsk(value: $.Orphan<ChatPayload>): void {
    $.utils.setUint16(2, 5, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownAsk(): $.Orphan<ChatPayload> {
    return $.utils.disown(this.ask);
  }
  get ask(): ChatPayload {
    $.utils.testWhich("ask", $.utils.getUint16(2, this), 5, this);
    return $.utils.getStruct(7, ChatPayload, this);
  }
  _hasAsk(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initAsk(): ChatPayload {
    $.utils.setUint16(2, 5, this);
    return $.utils.initStructAt(7, ChatPayload, this);
  }
  get _isAsk(): boolean {
    return $.utils.getUint16(2, this) === 5;
  }
  set ask(value: ChatPayload) {
    $.utils.setUint16(2, 5, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptBicture(value: $.Orphan<BicturePayload>): void {
    $.utils.setUint16(2, 6, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownBicture(): $.Orphan<BicturePayload> {
    return $.utils.disown(this.bicture);
  }
  get bicture(): BicturePayload {
    $.utils.testWhich("bicture", $.utils.getUint16(2, this), 6, this);
    return $.utils.getStruct(7, BicturePayload, this);
  }
  _hasBicture(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initBicture(): BicturePayload {
    $.utils.setUint16(2, 6, this);
    return $.utils.initStructAt(7, BicturePayload, this);
  }
  get _isBicture(): boolean {
    return $.utils.getUint16(2, this) === 6;
  }
  set bicture(value: BicturePayload) {
    $.utils.setUint16(2, 6, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptReplyChannelMessage(value: $.Orphan<ChannelMessagePayload>): void {
    $.utils.setUint16(2, 7, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownReplyChannelMessage(): $.Orphan<ChannelMessagePayload> {
    return $.utils.disown(this.replyChannelMessage);
  }
  get replyChannelMessage(): ChannelMessagePayload {
    $.utils.testWhich("replyChannelMessage", $.utils.getUint16(2, this), 7, this);
    return $.utils.getStruct(7, ChannelMessagePayload, this);
  }
  _hasReplyChannelMessage(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initReplyChannelMessage(): ChannelMessagePayload {
    $.utils.setUint16(2, 7, this);
    return $.utils.initStructAt(7, ChannelMessagePayload, this);
  }
  get _isReplyChannelMessage(): boolean {
    return $.utils.getUint16(2, this) === 7;
  }
  set replyChannelMessage(value: ChannelMessagePayload) {
    $.utils.setUint16(2, 7, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptReplyInteractionEdit(value: $.Orphan<InteractionEditPayload>): void {
    $.utils.setUint16(2, 8, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownReplyInteractionEdit(): $.Orphan<InteractionEditPayload> {
    return $.utils.disown(this.replyInteractionEdit);
  }
  get replyInteractionEdit(): InteractionEditPayload {
    $.utils.testWhich("replyInteractionEdit", $.utils.getUint16(2, this), 8, this);
    return $.utils.getStruct(7, InteractionEditPayload, this);
  }
  _hasReplyInteractionEdit(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initReplyInteractionEdit(): InteractionEditPayload {
    $.utils.setUint16(2, 8, this);
    return $.utils.initStructAt(7, InteractionEditPayload, this);
  }
  get _isReplyInteractionEdit(): boolean {
    return $.utils.getUint16(2, this) === 8;
  }
  set replyInteractionEdit(value: InteractionEditPayload) {
    $.utils.setUint16(2, 8, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptMessageReceived(value: $.Orphan<MessageReceivedPayload>): void {
    $.utils.setUint16(2, 9, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownMessageReceived(): $.Orphan<MessageReceivedPayload> {
    return $.utils.disown(this.messageReceived);
  }
  get messageReceived(): MessageReceivedPayload {
    $.utils.testWhich("messageReceived", $.utils.getUint16(2, this), 9, this);
    return $.utils.getStruct(7, MessageReceivedPayload, this);
  }
  _hasMessageReceived(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initMessageReceived(): MessageReceivedPayload {
    $.utils.setUint16(2, 9, this);
    return $.utils.initStructAt(7, MessageReceivedPayload, this);
  }
  get _isMessageReceived(): boolean {
    return $.utils.getUint16(2, this) === 9;
  }
  set messageReceived(value: MessageReceivedPayload) {
    $.utils.setUint16(2, 9, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptDevproxyCommand(value: $.Orphan<DevProxyCommandPayload>): void {
    $.utils.setUint16(2, 10, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownDevproxyCommand(): $.Orphan<DevProxyCommandPayload> {
    return $.utils.disown(this.devproxyCommand);
  }
  get devproxyCommand(): DevProxyCommandPayload {
    $.utils.testWhich("devproxyCommand", $.utils.getUint16(2, this), 10, this);
    return $.utils.getStruct(7, DevProxyCommandPayload, this);
  }
  _hasDevproxyCommand(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initDevproxyCommand(): DevProxyCommandPayload {
    $.utils.setUint16(2, 10, this);
    return $.utils.initStructAt(7, DevProxyCommandPayload, this);
  }
  get _isDevproxyCommand(): boolean {
    return $.utils.getUint16(2, this) === 10;
  }
  set devproxyCommand(value: DevProxyCommandPayload) {
    $.utils.setUint16(2, 10, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptConnectorInvoke(value: $.Orphan<ConnectorInvokePayload>): void {
    $.utils.setUint16(2, 11, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownConnectorInvoke(): $.Orphan<ConnectorInvokePayload> {
    return $.utils.disown(this.connectorInvoke);
  }
  get connectorInvoke(): ConnectorInvokePayload {
    $.utils.testWhich("connectorInvoke", $.utils.getUint16(2, this), 11, this);
    return $.utils.getStruct(7, ConnectorInvokePayload, this);
  }
  _hasConnectorInvoke(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initConnectorInvoke(): ConnectorInvokePayload {
    $.utils.setUint16(2, 11, this);
    return $.utils.initStructAt(7, ConnectorInvokePayload, this);
  }
  get _isConnectorInvoke(): boolean {
    return $.utils.getUint16(2, this) === 11;
  }
  set connectorInvoke(value: ConnectorInvokePayload) {
    $.utils.setUint16(2, 11, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptWebhookEvent(value: $.Orphan<WebhookEventPayload>): void {
    $.utils.setUint16(2, 12, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownWebhookEvent(): $.Orphan<WebhookEventPayload> {
    return $.utils.disown(this.webhookEvent);
  }
  get webhookEvent(): WebhookEventPayload {
    $.utils.testWhich("webhookEvent", $.utils.getUint16(2, this), 12, this);
    return $.utils.getStruct(7, WebhookEventPayload, this);
  }
  _hasWebhookEvent(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initWebhookEvent(): WebhookEventPayload {
    $.utils.setUint16(2, 12, this);
    return $.utils.initStructAt(7, WebhookEventPayload, this);
  }
  get _isWebhookEvent(): boolean {
    return $.utils.getUint16(2, this) === 12;
  }
  set webhookEvent(value: WebhookEventPayload) {
    $.utils.setUint16(2, 12, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptEgressRequest(value: $.Orphan<EgressRequestPayload>): void {
    $.utils.setUint16(2, 13, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownEgressRequest(): $.Orphan<EgressRequestPayload> {
    return $.utils.disown(this.egressRequest);
  }
  get egressRequest(): EgressRequestPayload {
    $.utils.testWhich("egressRequest", $.utils.getUint16(2, this), 13, this);
    return $.utils.getStruct(7, EgressRequestPayload, this);
  }
  _hasEgressRequest(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initEgressRequest(): EgressRequestPayload {
    $.utils.setUint16(2, 13, this);
    return $.utils.initStructAt(7, EgressRequestPayload, this);
  }
  get _isEgressRequest(): boolean {
    return $.utils.getUint16(2, this) === 13;
  }
  set egressRequest(value: EgressRequestPayload) {
    $.utils.setUint16(2, 13, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptApplicationRequest(value: $.Orphan<ApplicationRequestPayload>): void {
    $.utils.setUint16(2, 14, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownApplicationRequest(): $.Orphan<ApplicationRequestPayload> {
    return $.utils.disown(this.applicationRequest);
  }
  get applicationRequest(): ApplicationRequestPayload {
    $.utils.testWhich("applicationRequest", $.utils.getUint16(2, this), 14, this);
    return $.utils.getStruct(7, ApplicationRequestPayload, this);
  }
  _hasApplicationRequest(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initApplicationRequest(): ApplicationRequestPayload {
    $.utils.setUint16(2, 14, this);
    return $.utils.initStructAt(7, ApplicationRequestPayload, this);
  }
  get _isApplicationRequest(): boolean {
    return $.utils.getUint16(2, this) === 14;
  }
  set applicationRequest(value: ApplicationRequestPayload) {
    $.utils.setUint16(2, 14, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptRegistryInvoke(value: $.Orphan<RegistryInvokePayload>): void {
    $.utils.setUint16(2, 15, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownRegistryInvoke(): $.Orphan<RegistryInvokePayload> {
    return $.utils.disown(this.registryInvoke);
  }
  get registryInvoke(): RegistryInvokePayload {
    $.utils.testWhich("registryInvoke", $.utils.getUint16(2, this), 15, this);
    return $.utils.getStruct(7, RegistryInvokePayload, this);
  }
  _hasRegistryInvoke(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initRegistryInvoke(): RegistryInvokePayload {
    $.utils.setUint16(2, 15, this);
    return $.utils.initStructAt(7, RegistryInvokePayload, this);
  }
  get _isRegistryInvoke(): boolean {
    return $.utils.getUint16(2, this) === 15;
  }
  set registryInvoke(value: RegistryInvokePayload) {
    $.utils.setUint16(2, 15, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptMetadataQuery(value: $.Orphan<MetadataQueryPayload>): void {
    $.utils.setUint16(2, 16, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownMetadataQuery(): $.Orphan<MetadataQueryPayload> {
    return $.utils.disown(this.metadataQuery);
  }
  get metadataQuery(): MetadataQueryPayload {
    $.utils.testWhich("metadataQuery", $.utils.getUint16(2, this), 16, this);
    return $.utils.getStruct(7, MetadataQueryPayload, this);
  }
  _hasMetadataQuery(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initMetadataQuery(): MetadataQueryPayload {
    $.utils.setUint16(2, 16, this);
    return $.utils.initStructAt(7, MetadataQueryPayload, this);
  }
  get _isMetadataQuery(): boolean {
    return $.utils.getUint16(2, this) === 16;
  }
  set metadataQuery(value: MetadataQueryPayload) {
    $.utils.setUint16(2, 16, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  _adoptAttestInvoke(value: $.Orphan<AttestInvokePayload>): void {
    $.utils.setUint16(2, 17, this);
    $.utils.adopt(value, $.utils.getPointer(7, this));
  }
  _disownAttestInvoke(): $.Orphan<AttestInvokePayload> {
    return $.utils.disown(this.attestInvoke);
  }
  get attestInvoke(): AttestInvokePayload {
    $.utils.testWhich("attestInvoke", $.utils.getUint16(2, this), 17, this);
    return $.utils.getStruct(7, AttestInvokePayload, this);
  }
  _hasAttestInvoke(): boolean {
    return !$.utils.isNull($.utils.getPointer(7, this));
  }
  _initAttestInvoke(): AttestInvokePayload {
    $.utils.setUint16(2, 17, this);
    return $.utils.initStructAt(7, AttestInvokePayload, this);
  }
  get _isAttestInvoke(): boolean {
    return $.utils.getUint16(2, this) === 17;
  }
  set attestInvoke(value: AttestInvokePayload) {
    $.utils.setUint16(2, 17, this);
    $.utils.copyFrom(value, $.utils.getPointer(7, this));
  }
  toString(): string { return "EventEnvelope_Payload_" + super.toString(); }
  which(): EventEnvelope_Payload_Which {
    return $.utils.getUint16(2, this) as EventEnvelope_Payload_Which;
  }
}
export class EventEnvelope extends $.Struct {
  static readonly _capnp = {
    displayName: "EventEnvelope",
    id: "ea799f50bc6beec6",
    size: new $.ObjectSize(8, 8),
  };
  get v(): number {
    return $.utils.getUint16(0, this);
  }
  set v(value: number) {
    $.utils.setUint16(0, value, this);
  }
  get type(): string {
    return $.utils.getText(0, this);
  }
  set type(value: string) {
    $.utils.setText(0, value, this);
  }
  get id(): string {
    return $.utils.getText(1, this);
  }
  set id(value: string) {
    $.utils.setText(1, value, this);
  }
  get occurredAt(): string {
    return $.utils.getText(2, this);
  }
  set occurredAt(value: string) {
    $.utils.setText(2, value, this);
  }
  get source(): string {
    return $.utils.getText(3, this);
  }
  set source(value: string) {
    $.utils.setText(3, value, this);
  }
  get actor(): EventEnvelope_Actor {
    return $.utils.getAs(EventEnvelope_Actor, this);
  }
  _initActor(): EventEnvelope_Actor {
    return $.utils.getAs(EventEnvelope_Actor, this);
  }
  get guildId(): string {
    return $.utils.getText(6, this);
  }
  set guildId(value: string) {
    $.utils.setText(6, value, this);
  }
  get payload(): EventEnvelope_Payload {
    return $.utils.getAs(EventEnvelope_Payload, this);
  }
  _initPayload(): EventEnvelope_Payload {
    return $.utils.getAs(EventEnvelope_Payload, this);
  }
  toString(): string { return "EventEnvelope_" + super.toString(); }
}
DevProxyCommandPayload._Options = $.CompositeList(DevProxyCommandOption);
