// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = 0xa46a64eca8a0fa92n;
/**
* The body of every service queue hop: framed EventEnvelope bytes plus the
* signed identity-context token bound to their hash.
*
*/
export class ServiceMessage extends $.Struct {
  static readonly _capnp = {
    displayName: "ServiceMessage",
    id: "e7489163d7cb756a",
    size: new $.ObjectSize(0, 2),
  };
  _adoptEnvelope(value: $.Orphan<$.Data>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownEnvelope(): $.Orphan<$.Data> {
    return $.utils.disown(this.envelope);
  }
  get envelope(): $.Data {
    return $.utils.getData(0, this);
  }
  _hasEnvelope(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initEnvelope(length: number): $.Data {
    return $.utils.initData(0, length, this);
  }
  set envelope(value: $.Data) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  get idToken(): string {
    return $.utils.getText(1, this);
  }
  set idToken(value: string) {
    $.utils.setText(1, value, this);
  }
  toString(): string { return "ServiceMessage_" + super.toString(); }
}
/**
* A service's self-declared position, registered with the ServiceRegistry.
*
*/
export class ServiceManifest extends $.Struct {
  static readonly _capnp = {
    displayName: "ServiceManifest",
    id: "fbeb3d3bcdb17662",
    size: new $.ObjectSize(0, 5),
  };
  get service(): string {
    return $.utils.getText(0, this);
  }
  set service(value: string) {
    $.utils.setText(0, value, this);
  }
  get zone(): string {
    return $.utils.getText(1, this);
  }
  set zone(value: string) {
    $.utils.setText(1, value, this);
  }
  _adoptTargets(value: $.Orphan<$.List<string>>): void {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownTargets(): $.Orphan<$.List<string>> {
    return $.utils.disown(this.targets);
  }
  get targets(): $.List<string> {
    return $.utils.getList(2, $.TextList, this);
  }
  _hasTargets(): boolean {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initTargets(length: number): $.List<string> {
    return $.utils.initList(2, $.TextList, length, this);
  }
  set targets(value: $.List<string>) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  _adoptOperations(value: $.Orphan<$.List<string>>): void {
    $.utils.adopt(value, $.utils.getPointer(3, this));
  }
  _disownOperations(): $.Orphan<$.List<string>> {
    return $.utils.disown(this.operations);
  }
  get operations(): $.List<string> {
    return $.utils.getList(3, $.TextList, this);
  }
  _hasOperations(): boolean {
    return !$.utils.isNull($.utils.getPointer(3, this));
  }
  _initOperations(length: number): $.List<string> {
    return $.utils.initList(3, $.TextList, length, this);
  }
  set operations(value: $.List<string>) {
    $.utils.copyFrom(value, $.utils.getPointer(3, this));
  }
  _adoptScopes(value: $.Orphan<$.List<string>>): void {
    $.utils.adopt(value, $.utils.getPointer(4, this));
  }
  _disownScopes(): $.Orphan<$.List<string>> {
    return $.utils.disown(this.scopes);
  }
  get scopes(): $.List<string> {
    return $.utils.getList(4, $.TextList, this);
  }
  _hasScopes(): boolean {
    return !$.utils.isNull($.utils.getPointer(4, this));
  }
  _initScopes(length: number): $.List<string> {
    return $.utils.initList(4, $.TextList, length, this);
  }
  set scopes(value: $.List<string>) {
    $.utils.copyFrom(value, $.utils.getPointer(4, this));
  }
  toString(): string { return "ServiceManifest_" + super.toString(); }
}
/**
* The registry's full state, returned over the SERVICE_REGISTRY binding.
*
*/
export class ManifestSnapshot extends $.Struct {
  static readonly _capnp = {
    displayName: "ManifestSnapshot",
    id: "ae1ac331e34909e1",
    size: new $.ObjectSize(0, 1),
  };
  static _Manifests: $.ListCtor<ServiceManifest>;
  _adoptManifests(value: $.Orphan<$.List<ServiceManifest>>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownManifests(): $.Orphan<$.List<ServiceManifest>> {
    return $.utils.disown(this.manifests);
  }
  get manifests(): $.List<ServiceManifest> {
    return $.utils.getList(0, ManifestSnapshot._Manifests, this);
  }
  _hasManifests(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initManifests(length: number): $.List<ServiceManifest> {
    return $.utils.initList(0, ManifestSnapshot._Manifests, length, this);
  }
  set manifests(value: $.List<ServiceManifest>) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string { return "ManifestSnapshot_" + super.toString(); }
}
ManifestSnapshot._Manifests = $.CompositeList(ServiceManifest);
