package webgen

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"jsmunro.me/platy/cli/internal/manifest"
	"jsmunro.me/platy/cli/internal/output"
)

var serviceNamePattern = regexp.MustCompile(`(?m)^service\s+(\w+)\s*\{`)

// Generate emits typed clients for each generated application based on its
// manifest flags: `web_client` produces infra/applications/<app>/web (browser
// client bound to the trust zone web auth SDK) and `service_client` produces
// infra/applications/<app>/service (worker-to-worker client wrapping the SDK
// connector — validate caller, chain identity, attach token — plus the
// session-proxy target). Apps without a flag get the stale module removed.
func Generate(root string, apps []string) {
	loaded := manifest.Load(root)
	for _, app := range apps {
		entry, ok := loaded.Applications[app]
		emit(root, app, "web", ok && entry.WebClient, renderWebClient)
		emit(root, app, "service", ok && entry.ServiceClient, renderServiceClient)
	}
}

func emit(root, app, kind string, enabled bool, render func(string, string) (string, error)) {
	dir := filepath.Join(root, "infra", "applications", app, kind)
	if !enabled {
		if err := os.RemoveAll(dir); err != nil {
			output.Fail("remove stale %s client for %s: %v", kind, app, err)
		}
		return
	}
	source, err := render(root, app)
	if err != nil {
		output.Fail("generate %s client for %s: %v", kind, app, err)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		output.Fail("generate %s client for %s: %v", kind, app, err)
	}
	if err := os.WriteFile(filepath.Join(dir, "index.ts"), []byte(source), 0o644); err != nil {
		output.Fail("generate %s client for %s: %v", kind, app, err)
	}
	output.Logger.Info("generated "+kind+" client", "app", app)
}

// protoService is one `service X {}` declaration and the generated TS module
// (relative to the app's web directory) that exports its descriptor.
type protoService struct {
	Name   string
	Module string
}

func renderWebClient(root string, app string) (string, error) {
	services, err := protoServices(root, app)
	if err != nil {
		return "", err
	}
	if len(services) == 0 {
		return "", fmt.Errorf("no service declarations under infra/proto/%s", app)
	}

	var b strings.Builder
	b.WriteString("// Code generated by `platy dev generate`. DO NOT EDIT.\n")
	b.WriteString("//\n")
	fmt.Fprintf(&b, "// Typed browser client for the %s application: binds the generated\n", app)
	b.WriteString("// Connect services to the trust zone web auth SDK. The page stays a dumb\n")
	b.WriteString("// client — it only needs an initialized TrustZoneWebAuth; the application\n")
	b.WriteString("// mints its own audience token server-side (session-chain pattern).\n")
	b.WriteString("import type { Client } from \"@connectrpc/connect\";\n\n")
	b.WriteString("import { webClient, type TrustZoneWebAuth, type WebClientOptions } from \"../../../sdk/web/src\";\n")
	for _, service := range services {
		fmt.Fprintf(&b, "import { %s } from \"%s\";\n", service.Name, service.Module)
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "export const APPLICATION = %q;\n", app)
	for _, service := range services {
		b.WriteString("\n")
		fmt.Fprintf(&b, "export const create%sClient = (auth: TrustZoneWebAuth, options?: WebClientOptions): Client<typeof %s> =>\n", service.Name, service.Name)
		fmt.Fprintf(&b, "  webClient(auth, APPLICATION, %s, options);\n", service.Name)
	}
	return b.String(), nil
}

// renderServiceClient emits the worker-to-worker hop: every factory receives
// a connection (endpoint, gateway, this worker's credential, transports) and
// the caller's verified identity; the SDK connector underneath validates,
// chains, and attaches the audience token before anything leaves.
func renderServiceClient(root string, app string) (string, error) {
	services, err := protoServices(root, app)
	if err != nil {
		return "", err
	}
	if len(services) == 0 {
		return "", fmt.Errorf("no service declarations under infra/proto/%s", app)
	}

	var b strings.Builder
	b.WriteString("// Code generated by `platy dev generate`. DO NOT EDIT.\n")
	b.WriteString("//\n")
	fmt.Fprintf(&b, "// Typed service-to-service client for the %s application. The factories\n", app)
	b.WriteString("// are thin bindings over the SDK connector transport, which owns every\n")
	b.WriteString("// cross-cutting concern — caller validation, identity chaining, token\n")
	b.WriteString("// attachment, boundary logging, and trace propagation — so neither this\n")
	b.WriteString("// generated layer nor application code ever re-implements it.\n")
	b.WriteString("import type { Client } from \"@connectrpc/connect\";\n\n")
	b.WriteString("import {\n")
	b.WriteString("  connectorServiceClient,\n")
	b.WriteString("  type ConnectorConfig,\n")
	b.WriteString("  type Identity,\n")
	b.WriteString("  type ProxyTarget,\n")
	b.WriteString("} from \"../../../sdk/ts/src\";\n")
	for _, service := range services {
		fmt.Fprintf(&b, "import { %s } from \"%s\";\n", service.Name, service.Module)
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "export const APPLICATION = %q;\n", app)
	fmt.Fprintf(&b, "export const RPC_PREFIX = %q;\n\n", "/"+app+".v1.")
	b.WriteString("// Connection to this application for one hop; application is fixed.\n")
	b.WriteString("export type Connection = Omit<ConnectorConfig, \"application\">;\n")
	for _, service := range services {
		b.WriteString("\n")
		fmt.Fprintf(&b, "export const create%sClient = (connection: Connection, identity: Identity): Client<typeof %s> =>\n", service.Name, service.Name)
		fmt.Fprintf(&b, "  connectorServiceClient({ ...connection, application: APPLICATION }, identity, %s);\n", service.Name)
	}
	b.WriteString("\n")
	b.WriteString("// proxyTarget plugs this application into a sessionProxy (BFF) hop.\n")
	b.WriteString("export const proxyTarget = (target: { endpoint: string; scopes?: string[]; fetch?: typeof fetch }): ProxyTarget => ({\n")
	b.WriteString("  prefix: RPC_PREFIX,\n")
	b.WriteString("  application: APPLICATION,\n")
	b.WriteString("  ...target,\n")
	b.WriteString("});\n")
	return b.String(), nil
}

func protoServices(root string, app string) ([]protoService, error) {
	protoRoot := filepath.Join(root, "infra", "proto")
	appRoot := filepath.Join(protoRoot, app)
	var services []protoService
	err := filepath.WalkDir(appRoot, func(path string, entry os.DirEntry, err error) error {
		if err != nil || entry.IsDir() || !strings.HasSuffix(path, ".proto") {
			return err
		}
		contents, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		relative, err := filepath.Rel(protoRoot, path)
		if err != nil {
			return err
		}
		module := "../server/" + strings.TrimSuffix(filepath.ToSlash(relative), ".proto") + "_pb"
		for _, match := range serviceNamePattern.FindAllStringSubmatch(string(contents), -1) {
			services = append(services, protoService{Name: match[1], Module: module})
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(services, func(i, j int) bool { return services[i].Name < services[j].Name })
	return services, nil
}
