"""Bundle editable AI config resources into the Python Worker module graph."""

import pprint
from pathlib import Path

root = Path(__file__).resolve().parents[1]
resources = root / "src/ragbot/ai_config"
contents = {
    p.name: p.read_text() for p in sorted(resources.iterdir()) if p.suffix in {".json", ".md"}
}
(root / "src/ragbot/_bundled.py").write_text(
    "# Generated by scripts/bundle_config.py; edit src/ragbot/ai_config instead.\n"
    + "FILES = "
    + pprint.pformat(contents, width=100)
    + "\n"
)
