import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "workers", "applications", "dev-proxy", "web", "dist");
const htmlPath = join(dist, "index.html");
const assetsDir = join(dist, "assets");
const outPath = join(root, "workers", "applications", "dev-proxy", "api", "middleware_client", "src", "page.ts");

if (!existsSync(htmlPath) || !existsSync(assetsDir)) {
  throw new Error("dev-proxy Vite build output is missing");
}

let html = readFileSync(htmlPath, "utf8");
const assets = readdirSync(assetsDir);

for (const asset of assets) {
  const assetPath = `/assets/${asset}`;
  const fullPath = join(assetsDir, asset);
  if (asset.endsWith(".js")) {
    const js = readFileSync(fullPath, "utf8");
    html = html.replace(
      new RegExp(`<script type="module" crossorigin src="${assetPath}"></script>`),
      () => `<script type="module">\n${js}\n</script>`,
    );
  }
  if (asset.endsWith(".css")) {
    const css = readFileSync(fullPath, "utf8");
    html = html.replace(
      new RegExp(`<link rel="stylesheet" crossorigin href="${assetPath}">`),
      () => `<style>\n${css}\n</style>`,
    );
  }
}

const source = [
  "// Generated by `npm run devproxy:page:build` from workers/applications/dev-proxy/web.",
  "// Do not edit this file by hand; edit the React app instead.",
  `export const DEV_PROXY_PAGE = ${JSON.stringify(html)};`,
  "",
].join("\n");

writeFileSync(outPath, source);
