// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import type { Client } from "@connectrpc/connect";

import { DeployService } from "../server/deploy/v1/deploy_service_pb";
import {
  connectorServiceClient,
  type ConnectorConfig,
  type Identity,
} from "../../../sdk/ts/src";

export const APPLICATION = "deploy";
export const RPC_PREFIX = "/deploy.v1.";

export type Connection = Omit<ConnectorConfig, "application">;

export const deployServiceClient = (
  connection: Connection,
  identity: Identity,
): Client<typeof DeployService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, DeployService);


