// Code generated by `platy dev generate`. DO NOT EDIT.
//
// Typed service-to-service client for the deploy application. The factories
// are thin bindings over the SDK connector transport, which owns every
// cross-cutting concern — caller validation, identity chaining, token
// attachment, boundary logging, and trace propagation — so neither this
// generated layer nor application code ever re-implements it.
import type { Client } from "@connectrpc/connect";

import {
  connectorServiceClient,
  type ConnectorConfig,
  type Identity,
  type ProxyTarget,
} from "../../../sdk/ts/src";
import { DeployService } from "../server/deploy/v1/deploy_pb";

export const APPLICATION = "deploy";
export const RPC_PREFIX = "/deploy.v1.";

// Connection to this application for one hop; application is fixed.
export type Connection = Omit<ConnectorConfig, "application">;

export const createDeployServiceClient = (connection: Connection, identity: Identity): Client<typeof DeployService> =>
  connectorServiceClient({ ...connection, application: APPLICATION }, identity, DeployService);

// proxyTarget plugs this application into a sessionProxy (BFF) hop.
export const proxyTarget = (target: { endpoint: string; scopes?: string[]; fetch?: typeof fetch }): ProxyTarget => ({
  prefix: RPC_PREFIX,
  application: APPLICATION,
  ...target,
});
