// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import { serviceConnection, type Identity, type ServiceConnectionEnv } from "@platy/sdk";
import { ragbot } from "../../ragbot/service";

type Fetcher = { fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> };

export type TargetsEnv = ServiceConnectionEnv & {
  RAGBOT?: Fetcher;
  RAGBOT_ENDPOINT?: string;
};

const ragbotConnection = (env: TargetsEnv) =>
  serviceConnection(env, {
    endpoint: env.RAGBOT_ENDPOINT,
    binding: env.RAGBOT,
    scopes: ["ragbot/LeaderboardService.ListTotals"],
  });

// targets returns typed worker-to-worker clients for this app's manifest
// delegations. Each accessor throws when the target's endpoint or this
// worker's service credential is not configured.
export const targets = (env: TargetsEnv, identity: Identity) => ({
  ragbot: {
    leaderboardService: () => {
      const connection = ragbotConnection(env);
      if (!connection) {
        throw new Error("ragbot service connection unavailable (missing endpoint or credential)");
      }
      return ragbot.leaderboardServiceClient(connection, identity);
    },
  },
});

