// Code generated by buf generate (protoc-gen-platy-clients). DO NOT EDIT.
import type { Client } from "@connectrpc/connect";

import { ChatService } from "../server/ragbot/v1/chat_service_pb";
import { ConfigService } from "../server/ragbot/v1/config_service_pb";
import { DatabaseService } from "../server/ragbot/v1/database_service_pb";
import { GatewayControlService } from "../server/ragbot/v1/gateway_control_service_pb";
import { InteractionService } from "../server/ragbot/v1/interaction_service_pb";
import { LeaderboardService } from "../server/ragbot/v1/leaderboard_service_pb";
import { webClient, type BrowserAuth, type WebClientOptions } from "@platy/web";

export const APPLICATION = "ragbot";

export const ragbot = {
  chatServiceClient: (auth: BrowserAuth, options?: WebClientOptions): Client<typeof ChatService> =>
    webClient(auth, APPLICATION, ChatService, options),
  configServiceClient: (auth: BrowserAuth, options?: WebClientOptions): Client<typeof ConfigService> =>
    webClient(auth, APPLICATION, ConfigService, options),
  databaseServiceClient: (auth: BrowserAuth, options?: WebClientOptions): Client<typeof DatabaseService> =>
    webClient(auth, APPLICATION, DatabaseService, options),
  gatewayControlServiceClient: (auth: BrowserAuth, options?: WebClientOptions): Client<typeof GatewayControlService> =>
    webClient(auth, APPLICATION, GatewayControlService, options),
  interactionServiceClient: (auth: BrowserAuth, options?: WebClientOptions): Client<typeof InteractionService> =>
    webClient(auth, APPLICATION, InteractionService, options),
  leaderboardServiceClient: (auth: BrowserAuth, options?: WebClientOptions): Client<typeof LeaderboardService> =>
    webClient(auth, APPLICATION, LeaderboardService, options),
};

