package bffgen

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"jsmunro.me/platy/cli/internal/manifest"
	"jsmunro.me/platy/cli/internal/output"
)

const idpAudience = "idp"

type proxyTarget struct {
	Audience string
	Binding  string
	Endpoint string
	Scopes   []string
}

func Generate(root, app string) error {
	if manifest.HasProtoPackage(root, app) {
		return nil
	}
	loaded := manifest.Load(root)
	entry, ok := loaded.Applications[app]
	if !ok {
		return fmt.Errorf("application %s is not declared in applications.yaml", app)
	}
	if strings.TrimSpace(entry.Config) == "" {
		return nil
	}
	targets := proxyTargets(entry)
	if len(targets) == 0 {
		output.Logger.Info("skipping bff worker generation (no proxy delegations)", "app", app)
		return nil
	}
	workerDir := filepath.Join(root, filepath.FromSlash(strings.TrimSuffix(entry.Config, "/wrangler.jsonc")), "src")
	if err := os.MkdirAll(workerDir, 0o755); err != nil {
		return fmt.Errorf("create worker dir for %s: %w", app, err)
	}
	workerSource := renderWorker(app, targets)
	if err := os.WriteFile(filepath.Join(workerDir, "worker.ts"), []byte(workerSource), 0o644); err != nil {
		return fmt.Errorf("write worker for %s: %w", app, err)
	}
	wranglerPath := filepath.Join(root, filepath.FromSlash(entry.Config))
	wranglerSource, err := renderWrangler(root, loaded, app, entry, targets)
	if err != nil {
		return err
	}
	if err := os.WriteFile(wranglerPath, []byte(wranglerSource), 0o644); err != nil {
		return fmt.Errorf("write wrangler for %s: %w", app, err)
	}
	output.Logger.Info("generated bff worker", "app", app)
	return nil
}

func proxyTargets(app manifest.Application) []proxyTarget {
	var targets []proxyTarget
	for _, delegation := range app.Delegations {
		if delegation.Audience == idpAudience {
			continue
		}
		binding := strings.ToUpper(delegation.Audience)
		targets = append(targets, proxyTarget{
			Audience: delegation.Audience,
			Binding:  binding,
			Endpoint: binding + "_ENDPOINT",
			Scopes:   append([]string(nil), delegation.Scopes...),
		})
	}
	sort.Slice(targets, func(i, j int) bool { return targets[i].Audience < targets[j].Audience })
	return targets
}

func renderWorker(app string, targets []proxyTarget) string {
	var b strings.Builder
	b.WriteString("// Code generated by platy bffgen. DO NOT EDIT.\n\n")
	b.WriteString("import { createWebBffWorker } from \"../../../../sdk/ts/src\";\n\n")
	b.WriteString("export default createWebBffWorker({\n")
	fmt.Fprintf(&b, "  app: %q,\n", app)
	b.WriteString("  targets: [\n")
	for _, target := range targets {
		b.WriteString("    {\n")
		fmt.Fprintf(&b, "      audience: %q,\n", target.Audience)
		fmt.Fprintf(&b, "      binding: %q,\n", target.Binding)
		fmt.Fprintf(&b, "      endpoint: %q,\n", target.Endpoint)
		if len(target.Scopes) > 0 {
			b.WriteString("      scopes: [\n")
			for _, scope := range target.Scopes {
				fmt.Fprintf(&b, "        %q,\n", scope)
			}
			b.WriteString("      ],\n")
		}
		b.WriteString("    },\n")
	}
	b.WriteString("  ],\n")
	b.WriteString("});\n")
	return b.String()
}

func renderWrangler(root string, loaded *manifest.Manifest, app string, entry manifest.Application, targets []proxyTarget) (string, error) {
	host, err := endpointHost(entry.Endpoint)
	if err != nil {
		return "", err
	}
	routes := runWorkerFirstRoutes(targets)
	services := make([]map[string]string, 0, len(targets)+1)
	services = append(services, map[string]string{
		"binding": "AUTH_GATEWAY",
		"service": "auth-gateway",
	})
	vars := map[string]string{
		"AUTH_GATEWAY_URL":  "https://auth-gateway.jsmunro.me",
		"OTEL_SERVICE_NAME": app,
	}
	for _, target := range targets {
		targetApp, ok := loaded.Applications[target.Audience]
		if !ok {
			return "", fmt.Errorf("delegation audience %s is not declared in applications.yaml", target.Audience)
		}
		if strings.TrimSpace(targetApp.Worker) == "" {
			return "", fmt.Errorf("application %s has no worker name for bff binding", target.Audience)
		}
		services = append(services, map[string]string{
			"binding": target.Binding,
			"service": targetApp.Worker,
		})
		vars[target.Endpoint] = strings.TrimRight(targetApp.Endpoint, "/")
	}
	routesJSON, err := json.MarshalIndent(routes, "    ", "  ")
	if err != nil {
		return "", err
	}
	servicesJSON, err := json.MarshalIndent(services, "  ", "  ")
	if err != nil {
		return "", err
	}
	varsJSON, err := json.MarshalIndent(vars, "    ", "  ")
	if err != nil {
		return "", err
	}
	_ = root
	var b strings.Builder
	fmt.Fprintf(&b, "{\n  \"name\": %q,\n", app)
	b.WriteString("  \"main\": \"src/worker.ts\",\n")
	b.WriteString("  \"compatibility_date\": \"2026-04-23\",\n")
	b.WriteString("  \"compatibility_flags\": [\"nodejs_compat\"],\n")
	b.WriteString("  \"workers_dev\": false,\n")
	fmt.Fprintf(&b, "  \"routes\": [{\"pattern\": %q, \"custom_domain\": true}],\n", host)
	b.WriteString("  \"assets\": {\n")
	b.WriteString("    \"directory\": \"./public\",\n")
	b.WriteString("    \"binding\": \"ASSETS\",\n")
	b.WriteString("    \"not_found_handling\": \"single-page-application\",\n")
	fmt.Fprintf(&b, "    \"run_worker_first\": %s\n", routesJSON)
	b.WriteString("  },\n")
	fmt.Fprintf(&b, "  \"vars\": %s,\n", varsJSON)
	fmt.Fprintf(&b, "  \"services\": %s,\n", servicesJSON)
	b.WriteString("  \"observability\": {\n")
	b.WriteString("    \"logs\": {\"enabled\": true, \"invocation_logs\": true}\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String(), nil
}

func endpointHost(endpoint string) (string, error) {
	endpoint = strings.TrimSpace(endpoint)
	if endpoint == "" {
		return "", fmt.Errorf("application endpoint is required for bff wrangler routes")
	}
	if strings.HasPrefix(endpoint, "https://") {
		return strings.TrimPrefix(strings.TrimRight(endpoint, "/"), "https://"), nil
	}
	if strings.HasPrefix(endpoint, "http://") {
		return strings.TrimPrefix(strings.TrimRight(endpoint, "/"), "http://"), nil
	}
	return strings.TrimRight(endpoint, "/"), nil
}

func runWorkerFirstRoutes(targets []proxyTarget) []string {
	routes := []string{"/client/*"}
	seen := map[string]bool{"/client/*": true}
	for _, target := range targets {
		if len(target.Scopes) == 0 {
			pattern := fmt.Sprintf("/%s.v1.*", target.Audience)
			if !seen[pattern] {
				routes = append(routes, pattern)
				seen[pattern] = true
			}
			continue
		}
		for _, scope := range target.Scopes {
			pattern := scopeRoute(target.Audience, scope)
			if pattern == "" || seen[pattern] {
				continue
			}
			routes = append(routes, pattern)
			seen[pattern] = true
		}
	}
	sort.Strings(routes[1:])
	return routes
}

func scopeRoute(audience, scope string) string {
	parts := strings.SplitN(scope, "/", 2)
	if len(parts) != 2 {
		return ""
	}
	service := strings.SplitN(parts[1], ".", 2)[0]
	if service == "" {
		return ""
	}
	return fmt.Sprintf("/%s.v1.%s/*", audience, service)
}
